// 行程資料 — 2026/9/7（一）出發 → 9/16（三）返台
// 價格為 2026 年 7 月查證之參考值，出發前請以官網為準
window.TRIP = {
  days: [
    {
      id: 'd1', date: '9/7', weekday: '週一', title: '啟程：台北 → 倫敦（中午抵達，多賺半天！）',
      theme: '✈️ 阿聯酋 EK・經杜拜',
      transport: '推薦航班：阿聯酋航空 9/7 凌晨 00:30 TPE 起飛 → 杜拜轉機 2h45 → 當天中午 12:35 抵達蓋威克 LGW。進市區搭 Thameslink（約 £15，30–45 分鐘）或 Gatwick Express（£21.3 直達 Victoria）。',
      spots: [
        { time: '9/6 晚', name: '桃園機場報到（注意：前一晚！）', en: 'TPE Check-in', desc: '凌晨 00:30 起飛 = 9/6（日）晚上 21:30 前就要到機場報到，別搞錯日期！出發前 3 天以上完成 UK ETA 申請（£20）。', map: 'Taoyuan International Airport' },
        { time: '00:30', name: '起飛 → 杜拜轉機', en: 'TPE → DXB → LGW', desc: '第一段約 9.5 小時，正好睡覺；杜拜轉機 2h45 不趕不拖，逛一下全球最大機場免稅店再上第二段（約 8 小時）。', duration: '總程 19 小時 5 分' },
        { time: '12:35', name: '抵達倫敦蓋威克機場', en: 'London Gatwick (LGW)', desc: '入境走 eGate（台灣護照適用）。搭 Thameslink 進市區，感應信用卡或 Apple Pay 直接拍卡進站——不用買 Oyster 卡。', duration: '入境+進市區約 1.5 小時', map: 'Gatwick Airport' },
        { time: '15:00', name: '飯店 Check-in', en: 'Hotel Check-in', desc: '建議住宿區域：Paddington／South Kensington／King’s Cross（交通樞紐、治安好）。放好行李稍作休息。', tips: '超市 Tesco / Sainsbury’s / M&S 的即食餐是省錢好夥伴' },
        { time: '16:30', name: '南岸暖身散步・倫敦眼', en: 'South Bank & London Eye', desc: '中午就到的福利！沿泰晤士河南岸從倫敦眼散步到西敏橋，傍晚金色時刻拍大笨鐘，先把地標「預習」一遍。想搭倫敦眼可線上購票（£29 起）。', price: '散步免費／倫敦眼 £29 起', duration: '2 小時', tube: 'Waterloo', book: { label: '倫敦眼購票', url: 'https://www.londoneye.com/tickets-and-prices/' }, map: 'London Eye, South Bank, London' },
        { time: '19:00', name: '晚餐後早點休息', en: 'Early Night', desc: '時差調整關鍵日：撐到當地 21:00 再睡，隔天就能滿血開始正式行程。', tips: '南岸的 Wahaca 或飯店附近酒館簡單吃' },
      ],
      rainNote: '下午的南岸散步遇雨改成：',
      rainSpots: [
        { time: '16:30', name: '柯芬園（有頂棚）暖身逛', en: 'Covent Garden', desc: '玻璃頂棚市集不怕雨，Apple Market、街頭藝人、周邊小店先感受倫敦氛圍，晚餐在 Seven Dials Market 室內美食街解決。', price: '免費', duration: '2.5 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['行前必辦：UK ETA（官方 App 申請，£20，效期 2 年）', '英國插座為三孔 BS1363（G 型），記得帶轉接頭', '9 月倫敦約 11–19°C，早晚涼，帶薄外套 + 摺疊傘', '若最終訂的是其他航班（傍晚抵達版），下午行程直接略過即可'],
    },
    {
      id: 'd2', date: '9/8', weekday: '週二', title: '西敏經典：國會大廈・衛兵交接・國家美術館',
      theme: '🏛️ 倫敦必看首日',
      transport: '全天步行 + 地鐵。起點：Westminster 站（Jubilee / District / Circle 線）。',
      spots: [
        { time: '09:00', name: '大笨鐘與國會大廈', en: 'Big Ben & Houses of Parliament', desc: '西敏橋上拍大笨鐘全景，晨光角度最美。', price: '免費（外觀）', duration: '30 分鐘', tube: 'Westminster', map: 'Big Ben, London' },
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '英王加冕與皇室婚禮場地，牛頓、達爾文長眠於此。線上預訂較便宜且保證入場。', price: '£27（線上）/ £31（現場）', hours: '週一至五 09:30–15:30', duration: '1.5 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://tickets.westminster-abbey.org' }, map: 'Westminster Abbey, London' },
        { time: '11:00', name: '白金漢宮衛兵交接', en: 'Changing of the Guard', desc: '今天（9/8 週二）正好有衛兵交接！建議 10:40 前抵達卡位（維多利亞女王紀念碑階梯視野好）。', price: '免費', hours: '11:00 開始，約 45 分鐘', duration: '1–1.5 小時', tube: 'Green Park / St James’s Park', book: { label: '出發前確認場次', url: 'https://www.householddivision.org.uk/changing-the-guard-calendar' }, map: 'Buckingham Palace, London' },
        { time: '12:30', name: '聖詹姆士公園散步・午餐', en: 'St James’s Park', desc: '穿過公園往特拉法加廣場方向，途中在 Piccadilly 周邊吃午餐（推薦老字號 Fortnum & Mason 食品館或平價連鎖 Pret）。', price: '免費', duration: '1.5 小時', map: 'St James\'s Park, London' },
        { time: '14:30', name: '國家美術館', en: 'National Gallery', desc: '梵谷《向日葵》、莫內、達文西真跡，全部免費！2026 年適逢建館 200 週年。', price: '免費', hours: '每日 10:00–18:00', duration: '2 小時', tube: 'Charing Cross', book: { label: '官網資訊', url: 'https://www.nationalgallery.org.uk/visiting/plan-your-visit' }, map: 'National Gallery, London' },
        { time: '17:00', name: '特拉法加廣場 → 皮卡迪利圓環', en: 'Trafalgar Square → Piccadilly Circus', desc: '步行經過倫敦的「西門町」，感受市中心霓虹。晚餐推薦中國城（Chinatown）或蘇活區。', price: '免費', duration: '2 小時', map: 'Piccadilly Circus, London' },
      ],
      rainNote: '大雨時衛兵交接可能取消，改走全室內路線：',
      rainSpots: [
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '室內參觀不受天氣影響，照原計畫。', price: '£27（線上）', duration: '2 小時', tube: 'Westminster', map: 'Westminster Abbey, London' },
        { time: '12:00', name: '邱吉爾戰時密室', en: 'Churchill War Rooms', desc: '二戰時期的地下指揮部，原汁原味保存，歷史迷必看（全室內）。', price: '約 £32（線上）', hours: '09:30–18:00', duration: '2 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://www.iwm.org.uk/visits/churchill-war-rooms' }, map: 'Churchill War Rooms, London' },
        { time: '14:30', name: '國家美術館', en: 'National Gallery', desc: '免費室內看展，待到心滿意足。', price: '免費', duration: '2.5 小時', tube: 'Charing Cross', map: 'National Gallery, London' },
        { time: '17:30', name: '柯芬園（有頂棚）', en: 'Covent Garden', desc: '玻璃頂棚市集，雨天照樣逛：Apple Market 手作攤、街頭藝人、Ladurée 馬卡龍。', price: '免費', duration: '2 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['西敏寺週日不開放觀光，這天（週二）剛好', '午餐省錢招：Tesco / Boots 的 Meal Deal 約 £4–5'],
    },
    {
      id: 'd3', date: '9/9', weekday: '週三', title: '千年倫敦：倫敦塔・塔橋・波羅市場・聖保羅',
      theme: '🏰 歷史與美食日',
      transport: '地鐵至 Tower Hill 站起步，全天沿泰晤士河步行為主。',
      spots: [
        { time: '09:00', name: '倫敦塔', en: 'Tower of London', desc: '看王冠珠寶（Crown Jewels）要一開門就衝，可省排隊 1 小時。別錯過 Yeoman Warder（皇家衛士）免費導覽，幽默又精彩。', price: '£34.8（線上）', hours: '週二至六 09:00–17:30', duration: '3 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.hrp.org.uk/tower-of-london/visit/tickets-and-prices/' }, map: 'Tower of London' },
        { time: '12:15', name: '塔橋', en: 'Tower Bridge', desc: '登上塔橋走玻璃步道，俯瞰泰晤士河。時間緊可只在橋上拍照（免費）。', price: '£13.4（線上）/ 走過橋免費', hours: '09:30–18:00', duration: '1 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.towerbridge.org.uk/whats-on/entry-to-tower-bridge' }, map: 'Tower Bridge, London' },
        { time: '13:30', name: '波羅市場・午餐', en: 'Borough Market', desc: '倫敦最棒的美食市集（週三開始熱鬧）。必吃：Kappacasein 起司三明治、Padella 手工義大利麵（排隊名店）、生蠔攤。', price: '免費入場', hours: '週三至六最熱鬧，10:00–17:00', duration: '1.5 小時', tube: 'London Bridge', book: { label: '官網', url: 'https://boroughmarket.org.uk/visit-us/' }, map: 'Borough Market, London' },
        { time: '15:15', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '走千禧橋（哈利波特混血王子開場場景！）過河，登 528 階圓頂看倫敦全景。最後入場 16:00，要抓緊。', price: '£24–27（線上較便宜）', hours: '週三 10:00–16:30', duration: '1.5–2 小時', tube: 'St Paul’s', book: { label: '官網訂票', url: 'https://www.stpauls.co.uk/ticket-types-and-prices' }, map: 'St Paul\'s Cathedral, London' },
        { time: '17:30', name: '利德賀市場', en: 'Leadenhall Market', desc: '哈利波特「斜角巷」取景地！維多利亞式拱廊超好拍，此時商家剛下班氛圍最好。', price: '免費', duration: '30 分鐘', tube: 'Monument', map: 'Leadenhall Market, London' },
        { time: '18:00', name: '空中花園（需預約）', en: 'Sky Garden', desc: '35 樓免費空中花園看日落＋夜景。免費票每週一釋出 3 週後場次，搶到就是賺到；沒搶到可平日 walk-in 碰運氣或改買 The Shard（£28.5 起）。', price: '免費（需預約）', hours: '週一至五至 18:00', duration: '1 小時', tube: 'Monument', book: { label: '免費預約', url: 'https://skygarden.london/booking/' }, map: 'Sky Garden, 20 Fenchurch Street, London' },
      ],
      rainNote: '倫敦塔戶外區域多，大雨改全室內藝文路線：',
      rainSpots: [
        { time: '10:00', name: '泰特現代美術館', en: 'Tate Modern', desc: '免費現代藝術殿堂，由發電廠改建，10 樓觀景台免費看河景。', price: '免費', hours: '10:00–18:00', duration: '2.5 小時', tube: 'Southwark / Blackfriars', map: 'Tate Modern, London' },
        { time: '13:00', name: '波羅市場（有頂棚）・午餐', en: 'Borough Market', desc: '市場大部分有頂棚，雨天照吃不誤。', price: '免費入場', duration: '1.5 小時', tube: 'London Bridge', map: 'Borough Market, London' },
        { time: '15:00', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '全室內，照原計畫。', price: '£24–27', duration: '2 小時', tube: 'St Paul’s', map: 'St Paul\'s Cathedral, London' },
        { time: '17:30', name: '利德賀市場 + 空中花園', en: 'Leadenhall & Sky Garden', desc: '拱廊有頂棚、Sky Garden 全室內，雨天照走。', price: '免費', duration: '1.5 小時', tube: 'Monument', map: 'Leadenhall Market, London' },
      ],
      dayTips: ['倫敦塔 + 塔橋 + 聖保羅都排同一天門票不便宜（約 £75），預算有限可挑倫敦塔 + 其他免費景點', 'Padella 義大利麵不收訂位，13:30 後去排隊較短'],
    },
    {
      id: 'd4', date: '9/10', weekday: '週四', title: '一日遊①：牛津大學城 + Bicester 折扣村',
      theme: '🎓 學院巡禮與購物',
      transport: '去程：Paddington → Oxford 火車（直達約 1 小時，Advance 票 £6.5–10，提前買！）。牛津 → Bicester Village 火車僅 15 分鐘。回程：Bicester → Marylebone 直達約 50 分鐘（Chiltern Railways）。',
      spots: [
        { time: '07:50', name: '搭火車前往牛津', en: 'Paddington → Oxford', desc: '提前 12 週釋票，Advance 票最低 £6.5。用 GWR 官網或 Trainline 買電子票。', price: '£6.5–10（Advance）', duration: '1 小時', book: { label: 'GWR 訂票', url: 'https://www.gwr.com' }, map: 'Oxford Railway Station' },
        { time: '09:30', name: '基督堂學院', en: 'Christ Church College', desc: '哈利波特霍格華茲大餐廳的靈感原型！含大餐廳與座堂的多媒體導覽。門票每週五釋出，務必提早線上預約。', price: '£22.5–24.5', hours: '依學院行事曆，先查官網', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.chch.ox.ac.uk/visit/tickets-and-information' }, map: 'Christ Church, Oxford' },
        { time: '11:30', name: '波德里安圖書館・嘆息橋', en: 'Bodleian Library & Bridge of Sighs', desc: 'Radcliffe Camera 圓頂圖書館外觀必拍；想進 Divinity School（哈利波特醫護室場景）可參加 30 分鐘導覽（£12.5）。', price: '外觀免費／導覽 £12.5 起', duration: '1 小時', book: { label: '導覽預約', url: 'https://visit.bodleian.ox.ac.uk/tours/library-guided-tours' }, map: 'Radcliffe Camera, Oxford' },
        { time: '12:30', name: '牛津有頂市場・午餐', en: 'Covered Market', desc: '1774 年開業的老市場，推薦 Ben’s Cookies 創始店與傳統英式派。', price: '午餐約 £8–15', duration: '1 小時', map: 'Covered Market, Oxford' },
        { time: '14:30', name: '火車前往 Bicester Village', en: 'Oxford → Bicester Village', desc: '15 分鐘即達，車站出來步行 2 分鐘就是折扣村。', price: '約 £7', duration: '15 分鐘', map: 'Bicester Village Station' },
        { time: '15:00', name: 'Bicester 折扣村購物', en: 'Bicester Village', desc: 'Burberry、Gucci、Prada 等 150+ 品牌 outlet。注意：英國已取消遊客退稅，部分店家提供「免稅直郵海外」服務可扣 VAT。', price: '免費入場', hours: '週一至六 09:00–21:00', duration: '3.5 小時', book: { label: '官網', url: 'https://www.thebicestercollection.com/bicester-village/en' }, map: 'Bicester Village' },
        { time: '18:45', name: '火車回倫敦 Marylebone', en: 'Bicester → London Marylebone', desc: 'Chiltern Railways 直達約 50 分鐘，約每 30 分鐘一班。', price: '£22 起（Advance）', duration: '50 分鐘', book: { label: 'Chiltern 訂票', url: 'https://www.chilternrailways.co.uk/bicester-village-outlet-shopping-london' }, map: 'Marylebone Station, London' },
      ],
      rainNote: '牛津景點多為室內可照走；Bicester 是露天村大雨不好逛，改：',
      rainSpots: [
        { time: '09:30', name: '牛津學院巡禮（照原計畫）', en: 'Oxford Colleges', desc: '基督堂學院、波德里安導覽都在室內。加碼 Ashmolean 博物館（免費、英國最古老博物館）。', price: '同主方案', duration: '整個上午', map: 'Ashmolean Museum, Oxford' },
        { time: '14:30', name: '提早回倫敦 → Westfield 購物中心', en: 'Westfield London', desc: '歐洲最大室內購物中心之一（Shepherd’s Bush），品牌齊全，取代 Bicester 的購物行程。', price: '免費入場', hours: '至 21:00', duration: '3 小時', tube: 'Shepherd’s Bush', map: 'Westfield London, Shepherd\'s Bush' },
      ],
      dayTips: ['火車 Advance 票綁定班次、不可退款，時間抓寬鬆一點', '不想拉行李購物的話，Bicester 有寄物服務'],
    },
    {
      id: 'd5', date: '9/11', weekday: '週五', title: '大英博物館・王十字 9¾ 月台・西區音樂劇',
      theme: '🏺 文明瑰寶與劇院之夜',
      transport: '地鐵為主：Tottenham Court Road → King’s Cross → Covent Garden → 劇院區。',
      spots: [
        { time: '10:00', name: '大英博物館', en: 'British Museum', desc: '羅塞塔石碑、帕德嫩神殿雕刻、埃及木乃伊，世界文明一次看完，免費！建議線上預約免費時段票優先入場。注意：2026 西翼整修，部分展廳輪流關閉，出發前查官網。', price: '免費', hours: '10:00–17:00（週五至 20:30）', duration: '3 小時', tube: 'Tottenham Court Road', book: { label: '免費預約', url: 'https://www.britishmuseum.org/visit' }, map: 'British Museum, London' },
        { time: '13:30', name: '午餐：Dishoom King’s Cross', en: 'Dishoom', desc: '倫敦最紅的孟買風餐廳，培根捲餅（Bacon Naan）與黑扁豆咖哩必點。不接受 6 人以下訂位，13:30 後排隊較短。', price: '約 £15–25／人', duration: '1.5 小時', map: 'Dishoom King\'s Cross, London' },
        { time: '15:00', name: '王十字車站 9¾ 月台', en: 'Platform 9¾, King’s Cross', desc: '推行李車進牆的經典拍照點（免費排隊自拍，官方攝影另收費），旁邊就是哈利波特官方商店。', price: '免費', duration: '1 小時', tube: 'King’s Cross St. Pancras', map: 'Platform 9 3/4, King\'s Cross Station, London' },
        { time: '16:30', name: '柯芬園', en: 'Covent Garden', desc: '玻璃頂棚市集、街頭藝人、Neal’s Yard 彩色小巷。晚餐在此解決後步行去劇院。', price: '免費', duration: '2 小時', tube: 'Covent Garden', map: 'Covent Garden, London' },
        { time: '19:30', name: '西區音樂劇之夜', en: 'West End Musical', desc: '三選一：《獅子王》（視覺震撼，£28 起）、《女巫前傳 Wicked》（£23 起）、《歌劇魅影》（2026 慶 40 週年，£24 起）。用 TodayTix App 搶 £25 專區票或當日 Rush 票；Leicester Square 的 TKTS 亭賣當日折扣票。', price: '£25–80', duration: '2.5–3 小時', book: { label: 'TodayTix 訂票', url: 'https://www.todaytix.com/london' }, map: 'Lyceum Theatre, London' },
      ],
      rainNote: '本日行程幾乎全室內，天然防雨！大雨時只需把柯芬園戶外閒逛縮短。',
      rainSpots: null,
      dayTips: ['哈利波特迷加碼：舞台劇《被詛咒的孩子》經典兩部曲版本 2026 年 9 月是最後檔期（10 月起改單部新版），Palace Theatre，£15 起', '週五大英博物館開到 20:30，行程彈性大'],
    },
    {
      id: 'd6', date: '9/12', weekday: '週六', title: '一日遊②：科茲窩鄉村小鎮',
      theme: '🏡 英國最美鄉村',
      transport: '去程：Paddington → Moreton-in-Marsh 火車（約 1.5 小時）→ Pulhams 801 公車串遊小鎮（週六每小時一班）。建議下載 801 時刻表截圖備用。',
      spots: [
        { time: '07:20', name: '火車前往 Moreton-in-Marsh', en: 'Paddington → Moreton-in-Marsh', desc: '科茲窩唯一有幹線火車站的城鎮。Advance 票提早買約 £15–25。', price: '來回約 £30–40', duration: '1.5 小時', book: { label: 'GWR 訂票', url: 'https://www.gwr.com' }, map: 'Moreton-in-Marsh Station' },
        { time: '09:15', name: '801 公車 → 水上柏頓', en: 'Bourton-on-the-Water', desc: '「科茲窩的威尼斯」，Windrush 河穿鎮而過、石橋垂柳，蜂蜜色石屋群。可逛模型村（Model Village）與香水工坊。', price: '公車約 £3–4', hours: '車程約 30 分鐘', duration: '2.5 小時', map: 'Bourton-on-the-Water' },
        { time: '12:30', name: '午餐：河畔酒館', en: 'Pub Lunch', desc: '推薦 The Kingsbridge 或 Rose Tree 河景座位，點英式週末烤肉（Sunday Roast 週六也常供應）或炸魚薯條。', price: '£15–22／人', duration: '1.5 小時', map: 'The Kingsbridge, Bourton-on-the-Water' },
        { time: '14:20', name: '801 公車 → 斯托小鎮', en: 'Stow-on-the-Wold', desc: '科茲窩最高處的古董小鎮，必看 St Edward’s Church 被古樹包夾的「魔戒之門」，市集廣場喝下午茶。', price: '公車約 £3', duration: '2 小時', map: 'Stow-on-the-Wold' },
        { time: '16:50', name: '801 公車回 Moreton → 火車回倫敦', en: 'Return to London', desc: '回程火車約 18:00 發車，20:00 前回到 Paddington。', duration: '2 小時', map: 'Moreton-in-Marsh Station' },
      ],
      altNote: '想看海？備選方案：七姊妹白崖一日遊（自然震撼系）',
      altSpots: [
        { time: '08:00', name: '火車 Victoria → Seaford', en: 'London Victoria → Seaford', desc: '在 Lewes 轉車一次，全程約 1 小時 25 分。', price: '來回約 £25–32', duration: '1.5 小時', book: { label: 'Southern 訂票', url: 'https://www.southernrailway.com' }, map: 'Seaford Station' },
        { time: '10:00', name: 'Seaford Head 步道', en: 'Seaford Head', desc: '從 Seaford 海灘沿崖頂步道走到 Cuckmere Haven，這裡是拍七姊妹白崖經典角度（含海岸警備小屋前景）的最佳位置。', price: '免費', duration: '2.5 小時（來回約 5 公里）', map: 'Seaford Head, Seaford' },
        { time: '13:00', name: '午餐 + 七姊妹鄉村公園', en: 'Seven Sisters Country Park', desc: '在 Exceat 遊客中心午餐，沿 Cuckmere 河谷步道散步至海口近看白崖。', price: '免費', duration: '2.5 小時', map: 'Seven Sisters Country Park' },
        { time: '16:00', name: '12X 公車 → Brighton 傍晚遊', en: 'Brighton', desc: '搭 12X 到布萊頓（約 40 分鐘），逛 The Lanes 巷弄與布萊頓碼頭，吃海邊炸魚薯條後搭直達火車回倫敦（1 小時）。', price: '公車一日券 £9', duration: '2.5 小時', map: 'Brighton Palace Pier' },
      ],
      rainNote: '科茲窩與白崖都是戶外行程，遇雨建議改成：',
      rainSpots: [
        { time: '09:30', name: '溫莎城堡（室內為主）', en: 'Windsor Castle', desc: '英王行宮，State Apartments 與聖喬治教堂都在室內，雨天照樣精彩。Waterloo 直達火車 55 分鐘。', price: '£32（線上預購）', hours: '10:00–17:15（週二三休）', duration: '3 小時', book: { label: '官網訂票', url: 'https://www.rct.uk/visit/windsor-castle' }, map: 'Windsor Castle' },
        { time: '14:30', name: '回倫敦：V&A 博物館', en: 'V&A Museum', desc: '世界最大裝飾藝術博物館，免費，中庭咖啡廳是全球最美咖啡廳之一。', price: '免費', duration: '2.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
      ],
      dayTips: ['801 公車可用感應信用卡付款', '週六科茲窩遊客較多，早班火車出發才能悠閒', '拜柏里（Bibury）無大眾運輸可達，想去需參加倫敦出發的一日團（Rabbie’s 小團 £85 起）'],
    },
    {
      id: 'd7', date: '9/13', weekday: '週日', title: '一日遊③：華納兄弟哈利波特影城',
      theme: '⚡ 魔法世界朝聖',
      transport: 'Euston → Watford Junction 火車（直達 20 分鐘，£13.4，可感應付款）→ 官方接駁巴士 15 分鐘（出示影城門票免費搭）。',
      spots: [
        { time: '09:00', name: '火車前往 Watford Junction', en: 'Euston → Watford Junction', desc: '車站外跟著指標搭哈利波特彩繪接駁車，每 30 分鐘一班。', price: '火車 £13.4 + 接駁免費', duration: '40 分鐘', map: 'Watford Junction Station' },
        { time: '10:30', name: '華納兄弟哈利波特影城', en: 'Warner Bros. Studio Tour', desc: '原版拍攝場景：大餐廳、斜角巷、9¾ 月台、禁忌森林、霍格華茲城堡模型。奶油啤酒（Butterbeer）必喝！⚠️ 不售現場票，9 月場次常提前 6–8 週售罄——現在（7 月）就要訂！', price: '成人 £58.5 起', hours: '全程約 4–5 小時', duration: '4.5 小時', book: { label: '官網訂票（快售罄）', url: 'https://www.wbstudiotour.co.uk/tickets/' }, map: 'Warner Bros. Studio Tour London' },
        { time: '16:30', name: '回程 → 諾丁丘彩色街屋', en: 'Notting Hill', desc: '電影《新娘百分百》場景，Lancaster Road 彩色房子超好拍。注意：波多貝羅古董市集只在週五六全開，今天（週日）只能看街景——想逛市集的話改排 D8 前一天路過或起早。', price: '免費', duration: '1.5 小時', tube: 'Ladbroke Grove', map: 'Portobello Road, Notting Hill, London' },
        { time: '19:00', name: '晚餐：肯辛頓區', en: 'Dinner in Kensington', desc: '推薦 The Churchill Arms（滿牆鮮花的百年酒吧，裡面賣泰國菜！）。', price: '£12–20／人', duration: '1.5 小時', map: 'The Churchill Arms, Kensington, London' },
      ],
      rainNote: '影城全室內不受影響；傍晚諾丁丘街拍遇雨改：',
      rainSpots: [
        { time: '16:30', name: '國王十字聖潘克拉斯站巡禮', en: 'St Pancras', desc: '維多利亞哥德式火車站建築之美（室內），搭配 King’s Cross 旁的 Coal Drops Yard 文創街區（多有遮蔽）。', price: '免費', duration: '1.5 小時', tube: 'King’s Cross St. Pancras', map: 'St Pancras International, London' },
        { time: '18:30', name: '晚餐：Seven Dials Market（室內美食街）', en: 'Seven Dials Market', desc: '柯芬園旁的室內美食市場，各國料理一次滿足。', price: '£10–18／人', duration: '1.5 小時', tube: 'Covent Garden', map: 'Seven Dials Market, London' },
      ],
      dayTips: ['影城門票含中文語音導覽選項', '影城內餐點普通偏貴，可先吃早午餐再進場', '網站做好後第一件事：訂影城門票！'],
    },
    {
      id: 'd8', date: '9/14', weekday: '週一', title: '南肯辛頓博物館・英式下午茶・牛津街購物',
      theme: '🫖 優雅倫敦日',
      transport: '地鐵 South Kensington 站起步（有地下通道直達博物館），下午移動到 Soho / 牛津街。',
      spots: [
        { time: '10:00', name: '自然史博物館', en: 'Natural History Museum', desc: '哥德式「動物大教堂」建築本身就是景點，藍鯨骨架大廳、恐龍展廳、地震體驗，免費！', price: '免費', hours: '10:00–17:50', duration: '2 小時', tube: 'South Kensington', book: { label: '免費預約', url: 'https://www.nhm.ac.uk/visit.html' }, map: 'Natural History Museum, London' },
        { time: '12:15', name: 'V&A 博物館（快閃精華版）', en: 'V&A Museum', desc: '就在隔壁！挑重點看：時尚廳、珠寶廳、Cast Courts 石膏像中庭。附設咖啡廳是世界第一間博物館餐廳。', price: '免費', duration: '1.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
        { time: '14:00', name: '肯辛頓花園散步（宮殿外觀）', en: 'Kensington Gardens', desc: '肯辛頓宮今天（週一）休館，就在花園散步看宮殿外觀與黛安娜王妃紀念噴泉。想入內參觀的話要調到週三～週日（£24.7）。', price: '花園免費', duration: '1 小時', tube: 'High Street Kensington', map: 'Kensington Palace, London' },
        { time: '15:30', name: '英式下午茶', en: 'Afternoon Tea', desc: '三選一：Cutter & Squidge（Soho 創意甜點，£32.5）／Cinnamon Bazaar（英印風，£27.5）／奢華首選 Fortnum & Mason（£70 上下，難得體驗值得）。多數需預約。', price: '£27.5–75／人', duration: '1.5–2 小時', book: { label: 'Cutter & Squidge 預約', url: 'https://cutterandsquidge.com/pages/afternoon-tea' }, map: 'Cutter and Squidge, Soho, London' },
        { time: '17:30', name: '牛津街・攝政街購物', en: 'Oxford St & Regent St', desc: 'Selfridges 百貨、Liberty 百年木造百貨（必看建築）、Regent Street 弧形街景。運動迷可繞去 Lillywhites。', price: '免費入場', hours: '多數店營業至 21:00', duration: '2.5 小時', tube: 'Oxford Circus', map: 'Liberty London, Regent Street' },
      ],
      rainNote: '本日幾乎全室內，天然防雨！花園散步縮短即可。',
      rainSpots: null,
      dayTips: ['博物館雖免費，仍建議官網預約免排隊', '倫敦紀念品最划算的在超市：茶葉（Twinings / F&M）、餅乾、巧克力'],
    },
    {
      id: 'd9', date: '9/15', weekday: '週二', title: '格林威治半日遊 → 飛回台北',
      theme: '🚢 子午線上道別',
      transport: '上午：Uber Boat 遊船（Tower Pier → Greenwich，約 30 分鐘，App 購票較便宜）。下午回市區取行李 → 前往蓋威克 LGW（阿聯酋航班；Thameslink 或 Victoria 搭 Gatwick Express）。',
      spots: [
        { time: '09:00', name: 'Uber Boat 泰晤士河遊船', en: 'Uber Boat to Greenwich', desc: '從水上看塔橋與金絲雀碼頭天際線，兼具交通與觀光。App 或線上購票比現場便宜。', price: '單程約 £6.2 起', duration: '40 分鐘', book: { label: '購票', url: 'https://www.thamesclippers.com/plan-your-journey/ticket-information' }, map: 'Tower Millennium Pier, London' },
        { time: '10:00', name: '皇家天文台・本初子午線', en: 'Royal Observatory', desc: '雙腳橫跨東西半球！山丘上眺望格林威治全景與倫敦天際線。', price: '£24（線上）', hours: '10:00–17:00', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.rmg.co.uk/plan-your-visit/tickets-prices' }, map: 'Royal Observatory Greenwich' },
        { time: '11:45', name: '格林威治市集・午餐', en: 'Greenwich Market', desc: '有頂棚的百年手作市集（每日開放），各國小吃便宜好吃，順便買最後的紀念品。卡蒂薩克號帆船在旁邊可看外觀。', price: '免費入場', duration: '1.5 小時', map: 'Greenwich Market, London' },
        { time: '14:00', name: '回市區取行李 → 前往蓋威克', en: 'To Gatwick', desc: 'DLR + 地鐵回飯店取行李，搭 Thameslink（多站可上車，約 £15）或到 Victoria 搭 Gatwick Express（30 分鐘直達）。國際線起飛前 3 小時到機場。', price: '£15–21.3', duration: '2 小時', map: 'Gatwick Airport' },
        { time: '依票面', name: '班機起飛 → 杜拜 → 台北', en: 'LGW → DXB → TPE', desc: '阿聯酋經杜拜轉機回台北，抵達時間依班次（訂票時留意回程起飛時間，太早的話格林威治行程要縮短或取消）。', map: 'Gatwick Airport' },
      ],
      rainNote: '雨天改市區室內輕鬆版：',
      rainSpots: [
        { time: '10:00', name: '利柏堤百貨 & 攝政街最後採購', en: 'Liberty & Regent Street', desc: '室內購物補貨：茶葉、圍巾、伴手禮。', price: '免費入場', duration: '2 小時', tube: 'Oxford Circus', map: 'Liberty London' },
        { time: '12:30', name: '午餐 + M&S / Boots 掃貨', en: 'Last-minute Shopping', desc: '超市伴手禮（茶、餅乾、保養品）最後補貨，然後回飯店取行李前往機場。', duration: '1.5 小時', map: 'Marks and Spencer, Oxford Street, London' },
      ],
      dayTips: ['若航班是下午起飛，格林威治改為前一晚或直接取消，睡飽最重要', '英國已無購物退稅，別在機場排隊退稅（沒有這服務了）'],
    },
    {
      id: 'd10', date: '9/16', weekday: '週三', title: '抵達台北',
      theme: '🏠 返家',
      transport: '直飛約 13 小時，下午抵達桃園機場。',
      spots: [
        { time: '下午', name: '抵達桃園機場', en: 'Arrive TPE', desc: '歡迎回家！時差調整小訣竅：回程當天撐到台灣晚上再睡，隔天就能正常作息。', map: 'Taoyuan International Airport' },
      ],
      dayTips: ['回程行李注意：液體（酒、醬料）要托運；茶葉肉品入境規定先查關務署'],
    },
  ],
};
