// 行程資料 — 2026/9/7（一）出發 → 9/17（四）返程、9/18（五）抵台
// 價格為 2026 年 7 月查證之參考值，出發前請以官網為準
// 🤝 = 朋友可同行時段（週一全休；週三六 12:00–22:30 雙場；週日 12:00–17:00 早場；週二四五白天有空）
window.TRIP = {
  days: [
    {
      id: 'd1', date: '9/7', weekday: '週一', title: '啟程：台北 → 倫敦（中午抵達）',
      theme: '✈️ 阿聯酋 EK・經杜拜',
      friend: '朋友今天休假！中午抵達後直接會合，南岸散步＋接風晚餐一路同行。',
      transport: '推薦航班：阿聯酋航空 9/7 凌晨 00:30 TPE 起飛 → 杜拜轉機 2h45 → 當天中午 12:35 抵達蓋威克 LGW。進市區搭 Thameslink（約 £15，30–45 分鐘）或 Gatwick Express（£21.3 直達 Victoria）。本日交通費約 £18–24（機場線＋1–2 趟地鐵）。',
      spots: [
        { time: '9/6 晚', name: '桃園機場報到（注意：前一晚！）', en: 'TPE Check-in', desc: '凌晨 00:30 起飛 = 9/6（日）晚上 21:30 前就要到機場報到，別搞錯日期！出發前 3 天以上完成 UK ETA 申請（£20）。', map: 'Taoyuan International Airport' },
        { time: '00:30', name: '起飛 → 杜拜轉機', en: 'TPE → DXB → LGW', desc: '第一段約 9.5 小時，正好睡覺；杜拜轉機 2h45 不趕不拖，逛一下全球最大機場免稅店再上第二段（約 8 小時）。', duration: '總程 19 小時 5 分' },
        { time: '12:35', name: '抵達倫敦蓋威克機場', en: 'London Gatwick (LGW)', desc: '入境走 eGate（台灣護照適用）。搭 Thameslink 進市區，感應信用卡或 Apple Pay 直接拍卡進站——不用買 Oyster 卡。', duration: '入境+進市區約 1.5 小時', map: 'Gatwick Airport' },
        { time: '15:00', name: '朋友家放行李・會合', en: 'Drop Luggage', desc: '到朋友家安頓，記得帶台灣伴手禮！稍作休息後出門。', tips: '鳳梨酥、茶葉是英國留學圈最想念的味道' },
        { time: '16:30', name: '南岸暖身散步・倫敦眼', en: 'South Bank & London Eye', desc: '中午就到的福利！和朋友沿泰晤士河南岸從倫敦眼散步到西敏橋，傍晚金色時刻拍大笨鐘，先把地標「預習」一遍。', price: '散步免費／倫敦眼 £29 起', duration: '2 小時', tube: 'Waterloo', book: { label: '倫敦眼購票', url: 'https://www.londoneye.com/tickets-and-prices/' }, map: 'London Eye, South Bank, London' },
        { time: '19:00', name: '接風晚餐', en: 'Welcome Dinner', desc: '讓在地的朋友挑他的口袋名單！時差調整關鍵：撐到當地 21:00 再睡，隔天滿血開始。', tips: '南岸 Wahaca、Flat Iron 都是不踩雷選項' },
      ],
      rainNote: '下午的南岸散步遇雨改成：',
      rainSpots: [
        { time: '16:30', name: '柯芬園（有頂棚）暖身逛', en: 'Covent Garden', desc: '玻璃頂棚市集不怕雨，Apple Market、街頭藝人、周邊小店先感受倫敦氛圍，晚餐在 Seven Dials Market 室內美食街解決。', price: '免費', duration: '2.5 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['行前必辦：UK ETA（官方 App 申請，£20，效期 2 年）', '英國插座為三孔 BS1363（G 型），記得帶轉接頭', '9 月倫敦約 11–19°C，早晚涼，帶薄外套 + 摺疊傘'],
    },
    {
      id: 'd2', date: '9/8', weekday: '週二', title: '西敏經典：國會大廈・衛兵交接・國家美術館',
      theme: '🏛️ 倫敦必看首日',
      friend: '朋友白天有空（晚上有演出）：衛兵交接、國家美術館可同行，約 17:00 目送他去上班。',
      transport: '全天步行 + 地鐵。起點：Westminster 站（Jubilee / District / Circle 線）。本日交通費約 £5–7（景點間全步行，僅往返共 2–3 趟地鐵；日上限 £8.9 封頂）。',
      spots: [
        { time: '09:00', name: '大笨鐘與國會大廈', en: 'Big Ben & Houses of Parliament', desc: '西敏橋上拍大笨鐘全景，晨光角度最美。', price: '免費（外觀）', duration: '30 分鐘', tube: 'Westminster', map: 'Big Ben, London' },
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '英王加冕與皇室婚禮場地，牛頓、達爾文長眠於此。線上預訂較便宜且保證入場。', price: '£27（線上）/ £31（現場）', hours: '週一至五 09:30–15:30', duration: '1.5 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://tickets.westminster-abbey.org' }, map: 'Westminster Abbey, London' },
        { time: '11:00', name: '白金漢宮衛兵交接', en: 'Changing of the Guard', desc: '今天（9/8 週二）正好有衛兵交接！建議 10:40 前抵達卡位（維多利亞女王紀念碑階梯視野好）。', price: '免費', hours: '11:00 開始，約 45 分鐘', duration: '1–1.5 小時', tube: 'Green Park / St James’s Park', book: { label: '出發前確認場次', url: 'https://www.householddivision.org.uk/changing-the-guard-calendar' }, map: 'Buckingham Palace, London' },
        { time: '12:30', name: '聖詹姆士公園散步・午餐', en: 'St James’s Park', desc: '穿過公園往特拉法加廣場方向，途中在 Piccadilly 周邊吃午餐（推薦老字號 Fortnum & Mason 食品館或平價連鎖 Pret）。', price: '免費', duration: '1.5 小時', map: 'St James\'s Park, London' },
        { time: '14:30', name: '國家美術館', en: 'National Gallery', desc: '梵谷《向日葵》、莫內、達文西真跡，全部免費！2026 年適逢建館 200 週年。', price: '免費', hours: '每日 10:00–18:00', duration: '2 小時', tube: 'Charing Cross', book: { label: '官網資訊', url: 'https://www.nationalgallery.org.uk/visiting/plan-your-visit' }, map: 'National Gallery, London' },
        { time: '17:00', name: '特拉法加廣場 → 皮卡迪利圓環', en: 'Trafalgar Square → Piccadilly Circus', desc: '朋友去上班後自己散步逛市中心霓虹，順路逛萊斯特廣場的 LEGO 旗艦店（有大笨鐘樂高）與 M&M’s World；廣場旁的 Cecil Court 書店古董巷據說是「斜角巷」靈感來源之一，哈迷必繞。17:00–18:45 在中國城（Chinatown）吃晚餐。', price: '免費', duration: '2 小時', map: 'Cecil Court, London' },
        { time: '19:30', name: '🎭 歌劇魅影（選看・40 週年檔期）', en: 'The Phantom of the Opera', desc: '2026 正是魅影 40 週年（1986 年就在這座劇院首演），百老匯明星 Jordan Donica 主演！His Majesty’s Theatre 就在皮卡迪利圓環旁走路 2 分鐘，行程無縫接軌。官網 £25 起免手續費，40 週年需求高建議提前訂；選位首推 Stalls 中段（水晶吊燈就在頭上）。備選場次：9/10（四）牛津回來後、9/16（三）道別壓軸場；週三六另有 14:30 午場、週日休演。', price: '£25–120（Day Seats £37.5 每天 10:00 釋出）', hours: '19:30 開演，全長 2.5 小時', duration: '2.5 小時', tube: 'Piccadilly Circus', book: { label: '官網訂票', url: 'https://uk.thephantomoftheopera.com/tickets' }, map: 'His Majesty\'s Theatre, Haymarket, London' },
      ],
      rainNote: '大雨時衛兵交接可能取消，改走全室內路線：',
      rainSpots: [
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '室內參觀不受天氣影響，照原計畫。', price: '£27（線上）', duration: '2 小時', tube: 'Westminster', map: 'Westminster Abbey, London' },
        { time: '12:00', name: '邱吉爾戰時密室', en: 'Churchill War Rooms', desc: '二戰時期的地下指揮部，原汁原味保存，歷史迷必看（全室內）。', price: '約 £32（線上）', hours: '09:30–18:00', duration: '2 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://www.iwm.org.uk/visits/churchill-war-rooms' }, map: 'Churchill War Rooms, London' },
        { time: '14:30', name: '國家美術館', en: 'National Gallery', desc: '免費室內看展，待到心滿意足。', price: '免費', duration: '2.5 小時', tube: 'Charing Cross', map: 'National Gallery, London' },
        { time: '17:30', name: '柯芬園（有頂棚）', en: 'Covent Garden', desc: '玻璃頂棚市集，雨天照樣逛：Apple Market 手作攤、街頭藝人、Ladurée 馬卡龍。', price: '免費', duration: '2 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['西敏寺週日不開放觀光，這天（週二）剛好', '💡 免費聽世界級詩班：17:00 的 Evensong 晚禱可免費進西敏寺本堂（不用門票！），時間允許可以再回頭體驗', '午餐省錢招：Tesco / Boots 的 Meal Deal 約 £4–5'],
    },
    {
      id: 'd3', date: '9/9', weekday: '週三', title: '千年倫敦：倫敦塔・塔橋・波羅市場・聖保羅',
      theme: '🏰 歷史與美食日',
      friend: '朋友雙場日（12:00–22:30）：今天單飛，好好當個歷史迷。',
      transport: '地鐵至 Tower Hill 站起步，全天沿泰晤士河步行為主。本日交通費約 £5–7（沿河步行串點，僅 2–3 趟地鐵）。',
      spots: [
        { time: '09:00', name: '倫敦塔', en: 'Tower of London', desc: '看王冠珠寶（Crown Jewels）要一開門就衝，可省排隊 1 小時。別錯過 Yeoman Warder（皇家衛士）免費導覽，幽默又精彩。', price: '£34.8（線上）', hours: '週二至六 09:00–17:30', duration: '3 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.hrp.org.uk/tower-of-london/visit/tickets-and-prices/' }, map: 'Tower of London' },
        { time: '12:15', name: '塔橋', en: 'Tower Bridge', desc: '登上塔橋走玻璃步道，俯瞰泰晤士河。時間緊可只在橋上拍照（免費）。', price: '£13.4（線上）/ 走過橋免費', hours: '09:30–18:00', duration: '1 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.towerbridge.org.uk/whats-on/entry-to-tower-bridge' }, map: 'Tower Bridge, London' },
        { time: '12:45', name: '聖鄧斯坦教堂遺址花園', en: 'St Dunstan in the East', desc: '二戰炸毀的教堂殘骸長滿藤蔓，市中心的秘密花園——金融城上班族的私藏午休地，免費、超好拍，就在倫敦塔往塔橋的路上。', price: '免費', hours: '08:00–日落', duration: '20 分鐘', tube: 'Monument / Tower Hill', map: 'St Dunstan in the East, London' },
        { time: '13:45', name: '波羅市場・午餐', en: 'Borough Market', desc: '倫敦最棒的美食市集（週三開始熱鬧）。必吃：Kappacasein 起司三明治、Padella 手工義大利麵（排隊名店）、生蠔攤。飯後到市場旁的 Monmouth Coffee 喝一杯倫敦名店手沖；隔壁的 Southwark 大教堂（免費）與金鹿號帆船複製品也順路看看。', price: '免費入場', hours: '週三至六最熱鬧，10:00–17:00', duration: '1.5 小時', tube: 'London Bridge', book: { label: '官網', url: 'https://boroughmarket.org.uk/visit-us/' }, map: 'Borough Market, London' },
        { time: '15:15', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '走千禧橋（哈利波特混血王子開場場景！）過河，登 528 階圓頂看倫敦全景。最後入場 16:00，要抓緊。', price: '£24–27（線上較便宜）', hours: '週三 10:00–16:30', duration: '1.5–2 小時', tube: 'St Paul’s', book: { label: '官網訂票', url: 'https://www.stpauls.co.uk/ticket-types-and-prices' }, map: 'St Paul\'s Cathedral, London' },
        { time: '16:50', name: 'One New Change 頂樓平台', en: 'One New Change Rooftop', desc: '教堂正對面的購物中心，搭免費電梯上 6 樓露台——正對聖保羅圓頂的最佳拍照角度，遊客少、完全免費。', price: '免費', hours: '至 21:00 左右', duration: '20 分鐘', tube: 'St Paul’s', map: 'One New Change, London' },
        { time: '17:30', name: '利德賀市場', en: 'Leadenhall Market', desc: '哈利波特「斜角巷」取景地！維多利亞式拱廊超好拍，此時商家剛下班氛圍最好。', price: '免費', duration: '30 分鐘', tube: 'Monument', map: 'Leadenhall Market, London' },
        { time: '18:00', name: '空中花園（需預約）', en: 'Sky Garden', desc: '35 樓免費空中花園看日落＋夜景。免費票每週一釋出 3 週後場次；沒搶到有兩個免費備胎：隔壁 The Garden at 120（15 樓露天花園，免預約直接上）或 Horizon 22（254 公尺、倫敦最高免費觀景台，需官網預約）。', price: '免費（需預約）', hours: '週一至五至 18:00', duration: '1 小時', tube: 'Monument', book: { label: '免費預約', url: 'https://skygarden.london/booking/' }, map: 'Sky Garden, 20 Fenchurch Street, London' },
        { time: '21:30', name: '倫敦塔鑰匙典禮（選加，需提前搶票）', en: 'Ceremony of the Keys', desc: '倫敦塔 700 年不間斷的夜間鎖門儀式，全程 35 分鐘、莊嚴到起雞皮疙瘩。門票約 £10，每月初 13:00 釋出下下月票、秒殺——想去現在就要搶 9 月票！', price: '約 £10', hours: '每晚 21:30 準時、遲到不得入場', duration: '1 小時', tube: 'Tower Hill', book: { label: '官網搶票', url: 'https://www.hrp.org.uk/tower-of-london/whats-on/ceremony-of-the-keys/' }, map: 'Tower of London' },
      ],
      rainNote: '倫敦塔戶外區域多，大雨改全室內藝文路線：',
      rainSpots: [
        { time: '10:00', name: '泰特現代美術館', en: 'Tate Modern', desc: '免費現代藝術殿堂，由發電廠改建，10 樓觀景台免費看河景。', price: '免費', hours: '10:00–18:00', duration: '2.5 小時', tube: 'Southwark / Blackfriars', map: 'Tate Modern, London' },
        { time: '13:00', name: '波羅市場（有頂棚）・午餐', en: 'Borough Market', desc: '市場大部分有頂棚，雨天照吃不誤。', price: '免費入場', duration: '1.5 小時', tube: 'London Bridge', map: 'Borough Market, London' },
        { time: '15:00', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '全室內，照原計畫。', price: '£24–27', duration: '2 小時', tube: 'St Paul’s', map: 'St Paul\'s Cathedral, London' },
        { time: '17:30', name: '利德賀市場 + 空中花園', en: 'Leadenhall & Sky Garden', desc: '拱廊有頂棚、Sky Garden 全室內，雨天照走。', price: '免費', duration: '1.5 小時', tube: 'Monument', map: 'Leadenhall Market, London' },
      ],
      dayTips: ['倫敦塔 + 塔橋 + 聖保羅都排同一天門票不便宜（約 £75），預算有限可挑倫敦塔 + 其他免費景點', '不想付聖保羅門票？17:00 的 Evensong 晚禱可免費入內聽詩班（觀光參觀才收費）', '戲劇迷加碼：南岸的莎士比亞環球劇場站票只要 £5，體驗伊莉莎白式露天劇場', 'Padella 現在採虛擬排隊：到店掃 QR code 登記後先去逛市場，輪到會通知'],
    },
    {
      id: 'd4', date: '9/10', weekday: '週四', title: '一日遊①：牛津大學城（全日深度版）',
      theme: '🎓 學院巡禮',
      friend: '朋友白天有空、晚上有演出：若他願意早起，牛津可同行——搭 16:00 回程火車，18:00 前回到倫敦來得及上班。',
      transport: '去程：Paddington → Oxford 火車（直達約 1 小時，Advance 票 £6.5–10，提前買！）。牛津市區全程步行。本日交通費約 £18–25（火車來回 £13–20 ＋市區地鐵 £5）。',
      spots: [
        { time: '07:50', name: '搭火車前往牛津', en: 'Paddington → Oxford', desc: '提前 12 週釋票，Advance 票最低 £6.5。用 GWR 官網或 Trainline 買電子票。', price: '£6.5–10（Advance）', duration: '1 小時', book: { label: 'GWR 訂票', url: 'https://www.gwr.com' }, map: 'Oxford Railway Station' },
        { time: '09:30', name: '基督堂學院', en: 'Christ Church College', desc: '哈利波特霍格華茲大餐廳的靈感原型！含大餐廳與座堂的多媒體導覽。門票每週五釋出，務必提早線上預約。', price: '£22.5–24.5', hours: '依學院行事曆，先查官網', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.chch.ox.ac.uk/visit/tickets-and-information' }, map: 'Christ Church, Oxford' },
        { time: '11:30', name: '波德里安圖書館・嘆息橋', en: 'Bodleian Library & Bridge of Sighs', desc: 'Radcliffe Camera 圓頂圖書館外觀必拍；想進 Divinity School（哈利波特醫護室場景）可參加 30 分鐘導覽（£12.5）。', price: '外觀免費／導覽 £12.5 起', duration: '1 小時', book: { label: '導覽預約', url: 'https://visit.bodleian.ox.ac.uk/tours/library-guided-tours' }, map: 'Radcliffe Camera, Oxford' },
        { time: '12:30', name: '牛津有頂市場・午餐', en: 'Covered Market', desc: '1774 年開業的老市場，推薦 Ben’s Cookies 創始店與傳統英式派。', price: '午餐約 £8–15', duration: '1 小時', map: 'Covered Market, Oxford' },
        { time: '14:00', name: '徹韋爾河撐篙 或 艾許莫林博物館', en: 'Punting / Ashmolean', desc: '天氣好：Magdalen Bridge 船屋租撐篙船體驗劍河風情（約 £30–40／船／小時）；想輕鬆點就去 Ashmolean 博物館（免費，英國最古老博物館）。', price: '撐篙約 £30–40／艾許莫林免費', duration: '1.5 小時', book: { label: '撐篙資訊', url: 'https://www.oxfordpunting.co.uk' }, map: 'Magdalen Bridge Boathouse, Oxford' },
        { time: '16:00', name: '火車回倫敦', en: 'Oxford → Paddington', desc: '17:00 出頭回到 Paddington；朋友同行的話正好趕上晚上上班，你則可以續攤逛 Paddington 周邊或早點回家休息。', price: 'Advance 票另計', duration: '1 小時', map: 'Paddington Station, London' },
      ],
      rainNote: '牛津主要景點都在室內，雨天照走；撐篙改成：',
      rainSpots: [
        { time: '14:00', name: '艾許莫林博物館', en: 'Ashmolean Museum', desc: '免費、英國最古老的公共博物館，埃及木乃伊到拉斐爾素描都有，雨天待兩小時剛剛好。', price: '免費', hours: '10:00–17:00', duration: '2 小時', map: 'Ashmolean Museum, Oxford' },
      ],
      dayTips: ['火車 Advance 票綁定班次、不可退款，時間抓寬鬆一點', '嫌自助麻煩可跟團：KKday 有牛津+劍橋中文一日遊（約 NT$3,235），但自助搭火車更自由省錢', '🎭 魅影備選場次：17:15 回到 Paddington 後，趕 19:30 His Majesty’s Theatre 的晚場時間充裕（若 9/8 沒看成）'],
    },
    {
      id: 'd5', date: '9/11', weekday: '週五', title: '大英博物館・9¾ 月台・晚上看朋友的演出',
      theme: '🎭 文明瑰寶與朋友的舞台',
      friend: '今晚是重頭戲：去朋友的劇院看他的演出！晚上不排其他行程，散場等他一起回家。',
      transport: '地鐵為主：Tottenham Court Road → King’s Cross → Covent Garden → 劇院區。本日交通費約 £6–9（3–4 趟地鐵，日上限 £8.9 封頂）。',
      spots: [
        { time: '10:00', name: '大英博物館', en: 'British Museum', desc: '羅塞塔石碑、帕德嫩神殿雕刻、埃及木乃伊，世界文明一次看完，免費！建議線上預約免費時段票優先入場。注意：2026 西翼整修，部分展廳輪流關閉，出發前查官網。', price: '免費', hours: '10:00–17:00（週五至 20:30）', duration: '3 小時', tube: 'Tottenham Court Road', book: { label: '免費預約', url: 'https://www.britishmuseum.org/visit' }, map: 'British Museum, London' },
        { time: '13:30', name: '午餐：Dishoom King’s Cross', en: 'Dishoom', desc: '倫敦最紅的孟買風餐廳，培根捲餅（Bacon Naan）與黑扁豆咖哩必點。不接受 6 人以下訂位，13:30 後排隊較短。', price: '約 £15–25／人', duration: '1.5 小時', map: 'Dishoom King\'s Cross, London' },
        { time: '15:00', name: '王十字車站 9¾ 月台', en: 'Platform 9¾, King’s Cross', desc: '推行李車進牆的經典拍照點（免費排隊自拍，官方攝影另收費），旁邊就是哈利波特官方商店。拍完往車站後方走 5 分鐘：攝政運河上的百年駁船書店 Word on the Water（屋頂常有爵士演出）＋ Coal Drops Yard 文創街區。', price: '免費', duration: '1.5 小時', tube: 'King’s Cross St. Pancras', map: 'Word on the Water, King\'s Cross, London' },
        { time: '16:30', name: '回家休息・整裝', en: 'Rest & Refresh', desc: '下午提早收工回朋友家休息，晚上才有精神好好看秀。', duration: '1.5 小時' },
        { time: '18:00', name: '劇院附近輕鬆晚餐', en: 'Pre-show Dinner', desc: '在朋友的劇院附近簡單吃（西區劇院周邊很多 pre-theatre menu，兩道式約 £20–25）。時間夠可繞去柯芬園旁的 Neal’s Yard 彩虹小院（20 分鐘）拍照。', price: '£15–25／人', duration: '1 小時', map: 'Neal\'s Yard, Covent Garden, London' },
        { time: '19:30', name: '🎭 朋友的劇院看演出', en: 'Friend’s Show', desc: '今晚專程去捧場！記得先跟朋友確認場次與購票方式（劇組有時有親友票 comps 或員工折扣，先問他別急著自己買）。散場後在 stage door 等他，一起回家聊今晚的演出。', price: '票價依劇目（先問朋友）', duration: '3 小時' },
      ],
      rainNote: '本日行程幾乎全室內，天然防雨！大雨時只需把柯芬園戶外閒逛縮短。',
      rainSpots: null,
      dayTips: ['想另外看音樂劇（獅子王／Wicked／歌劇魅影）可挑其他晚上，用 TodayTix 搶 £25 專區票', '哈利波特迷加碼：舞台劇《被詛咒的孩子》兩部曲版本 2026/9 是最後檔期，可考慮週六日場', '大英博物館旁加碼：Sir John Soane’s Museum（免費、週三至日開），建築師故居塞滿古董的「藏品迷宮」', '哈迷場景補完：Australia House（古靈閣內景，只能看外觀）在 Temple 站附近', '週五大英博物館開到 20:30，白天行程可自由延長'],
    },
    {
      id: 'd6', date: '9/12', weekday: '週六', title: '一日遊②：科茲窩鄉村 或 溫莎巨石陣巴斯（二選一）',
      theme: '🏡 鄉村美景 vs 🏰 三大經典',
      friend: '朋友雙場日：單飛跟團剛剛好，晚上 22:30 後才見得到他。',
      transport: '兩個方案都是跟團、Victoria 周邊集合，全程遊覽車不用研究班次。用下方分頁切換比較，決定後再訂（兩團都可免費取消，也可以都先卡位）。本日交通費約 £5（車資含在團費，僅往返集合點地鐵）。',
      spots: [
        { time: '08:15', name: '方案A：科茲窩跟團出發', en: 'Cotswolds Tour', desc: '推薦團（原推薦 KKday 團已售罄，以下有位）：① 史特拉福＋科茲窩含拜伯里 NT$3,839（4.4 分、1K+ 訂購，加碼莎士比亞故居）② 中文團科茲窩雙線 NT$2,696（4.5 分）③ Golden Tours £75.65 含兩道式午餐（英文）。', price: 'NT$2,696–3,839／£75.65', duration: '全日約 10–11 小時', book: { label: 'KKday 科茲窩團列表', url: 'https://www.kkday.com/zh-tw/product/productlist?keyword=%E7%A7%91%E8%8C%B2%E7%AA%A9' }, map: 'Victoria Coach Station, London' },
        { time: '10:30', name: '拜伯里 Arlington Row', en: 'Bibury', desc: '威廉莫里斯口中「英格蘭最美村莊」，1380 年的織工小屋群是英國護照內頁圖案——大眾運輸到不了，跟團才吃得到這顆糖！（依所選團行程）', price: '含在團費', duration: '約 1 小時', map: 'Arlington Row, Bibury' },
        { time: '12:00', name: '伯福德・午餐', en: 'Burford', desc: '科茲窩門戶小鎮，主街斜坡兩側都是蜂蜜色石屋與古董店。Golden Tours 版在此含兩道式午餐。', price: '含在團費或自理 £15', duration: '1.5 小時', map: 'Burford, Cotswolds' },
        { time: '14:00', name: '水上柏頓／斯托／莎翁故居', en: 'Bourton / Stow / Stratford', desc: '依所選團造訪：「科茲窩的威尼斯」水上柏頓、斯托小鎮「魔戒之門」，或史特拉福的莎士比亞故居。', price: '含在團費', duration: '2 小時', map: 'Bourton-on-the-Water' },
        { time: '19:00', name: '回到倫敦 Victoria', en: 'Return to London', desc: '晚餐在 Victoria 周邊或回家附近解決，早點休息——明天是哈利波特日！', duration: '—', map: 'Victoria Station, London' },
      ],
      altNote: '方案B：溫莎城堡＋巨石陣＋巴斯中文團（4.5 分、1,413 則評論、售出 6K+；NT$3,407 門票自理／約 NT$7,462 中文導覽全含門票）。一天收三大經典，但每點只停 1.5 小時、節奏趕：',
      altSpots: [
        { time: '07:30', name: 'Grosvenor Gardens 集合（Victoria 站旁）', en: 'Tour Departure', desc: '08:00 準時發車、逾時不候（提早 30 分鐘到）。3 天前可免費取消，可先卡位。', price: 'NT$3,407 起', duration: '全日 12 小時', book: { label: 'KKday 訂購', url: 'https://www.kkday.com/zh-tw/product/1193-windsor-castle-stonehenge-bath-london-day-tour' }, map: 'Grosvenor Gardens, London SW1W 0DH' },
        { time: '10:00', name: '溫莎城堡', en: 'Windsor Castle', desc: '英國皇室千年行宮：國家外交大廳、瑪麗皇后玩偶屋、聖喬治教堂（女王長眠處），運氣好遇到衛兵交接。', price: '門票 £32（全含版已含）', duration: '1.5 小時', map: 'Windsor Castle' },
        { time: '13:00', name: '巨石陣', en: 'Stonehenge', desc: '5,000 年的史前謎團，UNESCO 世界遺產。草原上風大，帶防風外套。', price: '門票約 £30（全含版已含）', duration: '1.5 小時', map: 'Stonehenge' },
        { time: '16:00', name: '巴斯・羅馬浴場', en: 'Bath & Roman Baths', desc: '喬治王朝優雅古城＋英國唯一天然溫泉羅馬浴場，順逛普爾特尼橋與巴斯修道院。', price: '門票約 £25（全含版已含）', duration: '1.5 小時', map: 'Roman Baths, Bath' },
        { time: '20:00', name: '回到倫敦（Gloucester Road 站解散）', en: 'Return', desc: '評論提醒：當晚不要再排其他行程，回家好好休息——明天是哈利波特日！', map: 'Gloucester Road Station, London' },
      ],
      rainNote: '跟團雨天照出（兩案的室內比例：溫莎團較高）；都沒訂又遇大雨就改市區室內日：',
      rainSpots: [
        { time: '11:00', name: '國家肖像館', en: 'National Portrait Gallery', desc: '2023 年整修重開，從都鐸王朝到 Ed Sheeran 的英國名人肖像，免費。', price: '免費', hours: '10:30–18:00', duration: '2 小時', tube: 'Charing Cross', map: 'National Portrait Gallery, London' },
        { time: '14:30', name: '週六音樂劇日場', en: 'Saturday Matinee', desc: '週六下午場（14:30）票通常比晚場好買也便宜，用 TodayTix 或 TKTS 亭撿當日票。', price: '£25–60', duration: '3 小時', book: { label: 'TodayTix', url: 'https://www.todaytix.com/london' }, map: 'Leicester Square, London' },
      ],
      dayTips: ['兩團都可提前免費取消（A 團 3–4 天前／B 團 3 天前）——不確定就兩個都先卡位，出發前留一個', '若選方案 B：溫莎和 D8 的雨天備案重複，屆時 D8 雨天改去邱吉爾戰時密室或 Frameless', '自助火車版科茲窩仍可行：Paddington → Moreton-in-Marsh + 801 公車（來回約 £35–45，少了拜伯里但時間自主）'],
    },
    {
      id: 'd7', date: '9/13', weekday: '週日', title: '一日遊③：哈利波特影城＋週日烤肉之夜',
      theme: '⚡ 魔法世界朝聖',
      friend: '朋友早場（12:00–17:00）：你白天進影城，傍晚他下班正好會合吃 Sunday Roast！',
      transport: 'Euston → Watford Junction 火車（直達 20 分鐘，£13.4，可感應付款）→ 官方接駁巴士 15 分鐘（出示影城門票免費搭）。本日交通費約 £20–32（影城火車來回＋市區地鐵）。',
      spots: [
        { time: '09:00', name: '火車前往 Watford Junction', en: 'Euston → Watford Junction', desc: '車站外跟著指標搭哈利波特彩繪接駁車，每 30 分鐘一班。', price: '火車 £13.4 + 接駁免費', duration: '40 分鐘', map: 'Watford Junction Station' },
        { time: '10:30', name: '華納兄弟哈利波特影城', en: 'Warner Bros. Studio Tour', desc: '原版拍攝場景：大餐廳、斜角巷、9¾ 月台、禁忌森林、霍格華茲城堡模型。奶油啤酒必喝！⚠️ 不售現場票，9 月場次常提前 6–8 週售罄——現在就要訂！DIY（火車+門票約 £75）比含車套裝（KKday NT$4,852）省近四成。', price: '門票 £58.5 起', hours: '全程約 4–5 小時', duration: '4.5 小時', book: { label: '官網訂票（快售罄）', url: 'https://www.wbstudiotour.co.uk/tickets/' }, map: 'Warner Bros. Studio Tour London' },
        { time: '16:00', name: '回程進市區', en: 'Return', desc: '搭接駁＋火車回 Euston，順路回家放戰利品。', duration: '1 小時', map: 'Euston Station, London' },
        { time: '18:00', name: '週日烤肉晚餐（與朋友）', en: 'Sunday Roast Together', desc: '朋友 17:00 下班，一起吃英國週日傳統大餐：約克夏布丁＋烤牛肉＋肉汁。Hawksmoor 是名店（建議訂位），或讓朋友帶路去他愛的 gastropub。', price: '£25–40／人', duration: '2 小時', book: { label: 'Hawksmoor 訂位', url: 'https://thehawksmoor.com' }, map: 'Hawksmoor Seven Dials, London' },
      ],
      rainNote: '影城全室內不受影響；回程若下雨，晚餐前的空檔改逛室內的 St Pancras 車站建築與 Coal Drops Yard。',
      rainSpots: null,
      dayTips: ['影城門票含中文語音導覽選項', '影城內餐點普通偏貴，可先吃早午餐再進場', 'Sunday Roast 熱門店週日會滿，提早幾天訂位'],
    },
    {
      id: 'd8', date: '9/14', weekday: '週一', title: '一日遊④：七姊妹白崖（朋友休假日・全天同行！）',
      theme: '🤝 白崖健行雙人行',
      friend: '朋友全天休假——本週最重要的同行日！一起去看英格蘭最震撼的海岸線。',
      transport: '自助：Victoria → Seaford 火車（Lewes 轉車一次，約 1.5 小時，來回約 £25–32）。或跟中文團（超便宜）：KKday「陪爬陪拍」團 NT$1,228、Klook 版 NT$1,036。本日交通費：自助約 £37–44（火車來回＋沿海公車一日券 £9＋市區地鐵）／跟團約 £5。',
      spots: [
        { time: '08:00', name: '火車 Victoria → Seaford', en: 'London Victoria → Seaford', desc: '和朋友一起搭火車南下，在 Lewes 轉車一次。', price: '來回約 £25–32', duration: '1.5 小時', book: { label: 'Southern 訂票', url: 'https://www.southernrailway.com' }, map: 'Seaford Station' },
        { time: '10:00', name: 'Seaford Head 步道', en: 'Seaford Head', desc: '沿崖頂步道走到 Cuckmere Haven，這裡是拍七姊妹白崖經典角度（含海岸警備小屋前景）的最佳位置。', price: '免費', duration: '2.5 小時（來回約 5 公里）', map: 'Seaford Head, Seaford' },
        { time: '13:00', name: '午餐＋七姊妹鄉村公園', en: 'Seven Sisters Country Park', desc: '在 Exceat 遊客中心午餐，沿 Cuckmere 河谷步道散步至海口近看白崖。', price: '免費', duration: '2.5 小時', map: 'Seven Sisters Country Park' },
        { time: '16:00', name: '12X 公車 → 布萊頓傍晚遊', en: 'Brighton', desc: '搭 12X 到布萊頓（約 40 分鐘），逛 The Lanes 巷弄與布萊頓碼頭，海邊吃炸魚薯條，再搭直達火車回倫敦（約 1 小時）。', price: '公車一日券 £9', duration: '2.5 小時', map: 'Brighton Palace Pier' },
      ],
      altNote: '不想研究交通？中文團「陪爬陪拍」版（布萊頓+七姊妹+比奇角）：',
      altSpots: [
        { time: '08:00', name: '倫敦市區集合出發', en: 'Tour Departure', desc: 'KKday 中文團 NT$1,228（4.9 分、售出 300+，出發前建微信群）或 Klook 版 NT$1,036。含七姊妹健行、Beachy Head 燈塔拍照指導、布萊頓市區約 3 小時。', price: 'NT$1,036–1,228／人', duration: '全日 10 小時', book: { label: 'KKday 訂購', url: 'https://www.kkday.com/zh-tw/product/285517' }, map: 'Victoria Station, London' },
        { time: '10:30', name: '七姊妹白崖健行＋比奇角', en: 'Seven Sisters & Beachy Head', desc: '導遊帶路走最佳拍照路線，紅白條紋燈塔＋白色斷崖一次收。', price: '含在團費', duration: '3.5 小時', map: 'Beachy Head, Eastbourne' },
        { time: '15:00', name: '布萊頓自由活動', en: 'Brighton', desc: '皇家行宮外觀、The Lanes、碼頭遊樂園，約 21:00 回到倫敦。', price: '午餐自理', duration: '3 小時', map: 'Brighton Palace Pier' },
      ],
      rainNote: '白崖是純戶外行程，雨天和朋友改去溫莎（週一有開）：',
      rainSpots: [
        { time: '09:30', name: '溫莎城堡（室內為主）', en: 'Windsor Castle', desc: '英王行宮，State Apartments 與聖喬治教堂都在室內。Waterloo 直達火車 55 分鐘。', price: '£32（線上預購）', hours: '10:00–17:15（週二三休）', duration: '3 小時', book: { label: '官網訂票', url: 'https://www.rct.uk/visit/windsor-castle' }, map: 'Windsor Castle' },
        { time: '14:30', name: '回倫敦：V&A 博物館＋下午茶', en: 'V&A & Tea', desc: '世界最大裝飾藝術博物館（免費），中庭咖啡廳是全球最美咖啡廳之一，直接在裡面喝下午茶。', price: '免費入場', duration: '2.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
      ],
      dayTips: ['中文團出發前 2–4 天可免費取消，可先卡位、看天氣預報再決定', '崖頂無圍欄，拍照離邊緣至少 5 公尺', '白崖風大，防風外套必備'],
    },
    {
      id: 'd9', date: '9/15', weekday: '週二', title: '南肯辛頓博物館・英式下午茶・牛津街購物',
      theme: '🫖 優雅倫敦日',
      friend: '朋友白天有空：博物館＋下午茶可同行，17:00 過後他去上班、你繼續購物。',
      transport: '地鐵 South Kensington 站起步（地下通道直達博物館），下午移動到 Soho / 牛津街。本日交通費約 £6–9（多為步行＋2–3 趟地鐵，遠低於日上限）。',
      spots: [
        { time: '10:00', name: '自然史博物館', en: 'Natural History Museum', desc: '哥德式「動物大教堂」建築本身就是景點，藍鯨骨架大廳、恐龍展廳、地震體驗，免費！', price: '免費', hours: '10:00–17:50', duration: '2 小時', tube: 'South Kensington', book: { label: '免費預約', url: 'https://www.nhm.ac.uk/visit.html' }, map: 'Natural History Museum, London' },
        { time: '12:15', name: 'V&A 博物館（快閃精華版）', en: 'V&A Museum', desc: '就在隔壁！挑重點看：時尚廳、珠寶廳、Cast Courts 石膏像中庭。', price: '免費', duration: '1.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
        { time: '14:00', name: '肯辛頓花園・亞伯特紀念碑・海德公園', en: 'Kensington Gardens & Hyde Park', desc: '肯辛頓宮週二休館，改在花園散步看宮殿外觀；博物館對面金光閃閃的亞伯特紀念碑必拍。腳力夠可加碼荷蘭公園裡的京都庭園（日式庭園＋孔雀，走路 15 分鐘）；或改逛 Knightsbridge 的 Harrods（Jellycat 迷看口袋名單）。', price: '免費', duration: '1–1.5 小時', tube: 'High Street Kensington', map: 'Albert Memorial, Kensington Gardens, London' },
        { time: '15:30', name: '英式下午茶（與朋友）', en: 'Afternoon Tea', desc: '三選一：Cutter & Squidge（Soho 創意甜點，£32.5）／Cinnamon Bazaar（英印風，£27.5）／奢華首選 Fortnum & Mason（£70 上下）。多數需預約。', price: '£27.5–85／人', duration: '1.5–2 小時', book: { label: 'Cutter & Squidge 預約', url: 'https://cutterandsquidge.com/pages/afternoon-tea' }, map: 'Cutter and Squidge, Soho, London' },
        { time: '17:30', name: '牛津街・攝政街購物', en: 'Oxford St & Regent St', desc: 'Selfridges 百貨（4 樓有 Jellycat 專區，見口袋名單）、Liberty 百年木造百貨（必看建築）、Regent Street 弧形街景、Hamleys 玩具旗艦。', price: '免費入場', hours: '多數店營業至 21:00', duration: '2 小時', tube: 'Oxford Circus', map: 'Liberty London, Regent Street' },
        { time: '19:45', name: '晚餐：Mercato Mayfair', en: 'Mercato Mayfair', desc: '百年教堂改建的美食廣場——在彩繪玻璃與挑高圓頂下吃遍義式披薩、生蠔、亞洲料理，購物完走過去 10 分鐘。', price: '£10–20／人', hours: '至 22:00 左右', duration: '1.5 小時', tube: 'Bond Street', map: 'Mercato Mayfair, London' },
      ],
      rainNote: '本日幾乎全室內，天然防雨！花園散步縮短即可。',
      rainSpots: null,
      dayTips: ['博物館雖免費，仍建議官網預約免排隊', '購物段兩個免費文青繞路：Wallace Collection 華勒斯典藏館（貴族宅邸美術館，10:00–17:00，Bond St 旁）與 Daunt Books 敦特書店（倫敦最美書店，Marylebone）', '晚餐後還有力氣？搭兩站到 Chalk Farm 上櫻草丘（Primrose Hill）看免費天際線夜景', '倫敦紀念品最划算的在超市：茶葉（Twinings / F&M）、餅乾、巧克力'],
    },
    {
      id: 'd10', date: '9/16', weekday: '週三', title: '格林威治半日遊・肯辛頓宮・最後採買',
      theme: '🚢 子午線與宮殿',
      friend: '朋友雙場日：最後的單飛日，把想逛的補完。',
      transport: '上午：Uber Boat 遊船（Tower Pier → Greenwich，約 30 分鐘，App 購票較便宜）。下午地鐵回市區。本日交通費約 £14–18（遊船單程 £6.2 起＋DLR/地鐵數趟）。',
      spots: [
        { time: '09:00', name: 'Uber Boat 泰晤士河遊船', en: 'Uber Boat to Greenwich', desc: '從水上看塔橋與金絲雀碼頭天際線，兼具交通與觀光。App 或線上購票比現場便宜。', price: '單程約 £6.2 起', duration: '40 分鐘', book: { label: '購票', url: 'https://www.thamesclippers.com/plan-your-journey/ticket-information' }, map: 'Tower Millennium Pier, London' },
        { time: '10:00', name: '皇家天文台・本初子午線', en: 'Royal Observatory', desc: '雙腳橫跨東西半球！山丘上眺望格林威治全景與倫敦天際線。', price: '£24（線上）', hours: '10:00–17:00', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.rmg.co.uk/plan-your-visit/tickets-prices' }, map: 'Royal Observatory Greenwich' },
        { time: '11:30', name: '舊皇家海軍學院・皇后宅邸鬱金香梯', en: 'Old Royal Naval College & Queen\'s House', desc: '天文台下山途經——《雷神索爾》《加勒比海盜》都在這取景，巴洛克雙塔園區免費進入；旁邊免費的 Queen’s House 有全倫敦最好拍的 Tulip Stairs 藍色螺旋梯，別錯過！', price: '園區與皇后宅邸免費／Painted Hall 約 £15', duration: '45 分鐘', map: 'Queen\'s House, Greenwich' },
        { time: '12:15', name: '格林威治市集・午餐', en: 'Greenwich Market', desc: '有頂棚的百年手作市集（每日開放），各國小吃便宜好吃，順便買紀念品。卡蒂薩克號帆船在旁邊可看外觀。', price: '免費入場', duration: '1.5 小時', map: 'Greenwich Market, London' },
        { time: '14:00', name: '肯辛頓宮', en: 'Kensington Palace', desc: '黛安娜王妃故居，今天（週三）有開！State Apartments 與特展。時間不夠或想省門票就改逛海德公園。', price: '£24.7（線上）', hours: '週三至日 10:00–18:00', duration: '2 小時', tube: 'High Street Kensington', book: { label: '官網訂票', url: 'https://www.hrp.org.uk/kensington-palace/visit/tickets-and-prices/' }, map: 'Kensington Palace, London' },
        { time: '17:00', name: '最後採買・打包', en: 'Last Shopping & Packing', desc: '超市掃伴手禮（茶葉、餅乾、保養品），回家打包行李。明天中午前就要出門了。', duration: '2 小時', map: 'Marks and Spencer, Oxford Street, London' },
      ],
      rainNote: '雨天改全室內輕鬆版：',
      rainSpots: [
        { time: '10:00', name: '肯辛頓宮＋自然史補完', en: 'Kensington Palace', desc: '宮殿全室內；還沒逛夠的南肯辛頓博物館群也在附近。', price: '£24.7', duration: '3 小時', tube: 'High Street Kensington', map: 'Kensington Palace, London' },
        { time: '14:00', name: '利柏堤百貨＆攝政街室內採買', en: 'Liberty & Regent Street', desc: '室內購物補貨：茶葉、圍巾、伴手禮，順便打包前最後巡禮。', price: '免費入場', duration: '2.5 小時', tube: 'Oxford Circus', map: 'Liberty London' },
      ],
      dayTips: ['行李秤一下：阿聯酋經濟艙托運通常 25–35kg（依票種），伴手禮買太多要留意', '液體（酒、醬料）記得放托運', '🎭 魅影最終備選場：今晚 19:30 可當「道別倫敦」壓軸（週三另有 14:30 午場），但隔天要飛、自己衡量體力'],
    },
    {
      id: 'd11', date: '9/17', weekday: '週四', title: '道別倫敦 → 台北（9/18 抵達）',
      theme: '🏠 返程日',
      friend: '朋友白天有空：可以一起吃告別早午餐，甚至送你到車站。',
      transport: '前往蓋威克 LGW：Thameslink（約 £15）或 Victoria 搭 Gatwick Express（30 分鐘直達）。國際線起飛前 3 小時到機場。本日交通費約 £18–24（市區地鐵＋機場線）。',
      spots: [
        { time: '09:30', name: '告別早午餐（與朋友）', en: 'Farewell Brunch', desc: '和朋友吃頓悠閒的英式早午餐道別——Full English Breakfast 畫下句點。附近咖啡館或 Dishoom 都好。', price: '£12–20／人', duration: '1.5 小時', map: 'Dishoom Covent Garden, London' },
        { time: '11:30', name: '前往蓋威克機場', en: 'To Gatwick', desc: '取行李出發（依票面起飛時間回推 3 小時到機場；若是傍晚班機，上午還能加碼一個小景點）。', price: '£15–21.3', duration: '1.5 小時', map: 'Gatwick Airport' },
        { time: '依票面', name: '起飛 → 杜拜 → 台北', en: 'LGW → DXB → TPE', desc: '阿聯酋經杜拜轉機，9/18（五）抵達桃園。回程時差訣竅：抵台當天撐到晚上再睡。', map: 'Gatwick Airport' },
      ],
      dayTips: ['英國已無購物退稅，別在機場排隊找退稅櫃台（沒有這服務了）', '茶葉、肉品入境台灣規定先查關務署，火腿臘腸類不能帶'],
    },
  ],
};
