// 行程資料 — 2026/9/5（六）出發 → 9/17（四）返程、9/18（五）抵台（國泰經香港，已開票）
// 價格為 2026 年 7 月查證之參考值，出發前請以官網為準
// 🤝 = 朋友可同行時段（週一全休；週三六 12:00–22:30 雙場；週日 12:00–17:00 早場；週二四五白天有空）
window.TRIP = {
  days: [
    {
      id: 'd1', date: '9/5', weekday: '週六', title: '啟程：台北 → 香港 → 倫敦（晚上抵達）',
      theme: '✈️ 國泰 CX407＋CX253・已開票',
      friend: '今天不會見到朋友——晚上才落地，入住後傳個訊息報平安，約好明晚見。',
      stay: '住朋友家第 1 晚（9/5–9/11 共 6 晚）。⚠️ 約 22:45 才到，但住朋友家沒有商業入住時限——先跟朋友約好鑰匙／密碼，或等他看完週六場（22:30 下班）回來會合。',
      transport: 'CX407 台北 08:00 → 香港 10:00・轉機 3h25 → CX253 13:25 → 倫敦希斯洛 LHR T3 當晚 20:35。從機場到朋友家：Piccadilly 線直達市中心沿線（約 £5.6）或 Elizabeth 線 30 分鐘到 Paddington（約 £13.9）再轉乘，實際末段依朋友家位置。本日交通費約 £6–14。',
      spots: [
        { time: '06:00', name: '桃園機場報到', en: 'TPE Check-in', desc: '08:00 起飛，06:00 前到 T1 報到。出發前 3 天以上完成 UK ETA 申請（£20）；托運行李額度（Light 票種）先在官網確認。', map: 'Taoyuan International Airport' },
        { time: '08:00', name: '起飛 → 香港轉機', en: 'TPE → HKG', desc: '短程 2 小時到香港，轉機 3h25 同一航廈不趕不拖，吃個午餐再上長程段。', duration: '轉機 3 小時 25 分' },
        { time: '13:25', name: '香港 → 倫敦（長程段）', en: 'HKG → LHR', desc: '14 小時 10 分：策略是「前段醒、後段睡」——落地是倫敦晚上，下機直接睡最順。機上把時錶調成倫敦時間。', duration: '總程 19 小時 35 分' },
        { time: '20:35', name: '抵達希斯洛 T3', en: 'London Heathrow (LHR)', desc: '入境走 eGate（台灣護照適用，記得先辦好 ETA）。感應信用卡或 Apple Pay 直接拍卡進地鐵——不用買 Oyster 卡。', duration: '入境＋領行李約 1 小時', map: 'Heathrow Airport Terminal 3' },
        { time: '22:30', name: '入住・直接睡覺', en: 'Check-in & Sleep', desc: '今晚唯一任務：睡。落地時間就是倫敦人的睡覺時間，是調時差的完美劇本，別滑手機到半夜。', tips: '在機場或住處旁便利商店買瓶水和明早的簡單早餐' },
      ],
      rainNote: '移動日不受天氣影響。',
      rainSpots: null,
      dayTips: ['行前必辦：UK ETA（官方 App 申請，£20，效期 2 年）', '英國插座為三孔 BS1363（G 型），記得帶轉接頭', '9 月倫敦約 11–19°C，早晚涼，帶薄外套 + 摺疊傘'],
    },
    {
      id: 'd2', date: '9/6', weekday: '週日', title: '週日限定：東區市集日（時差緩衝）',
      theme: '🌸 花市與紅磚巷',
      friend: '朋友早場（12:00–17:00）：白天單飛逛市集，晚上他下班一起吃晚餐——行程的第一次會合！',
      stay: '住朋友家第 2 晚。',
      transport: '地鐵＋步行：東區三個市集彼此步行可達（Old Street／Liverpool Street 站起步）。本日交通費約 £8–11（Zone 1–3 日上限封頂）。',
      spots: [
        { time: '09:30', name: '哥倫比亞路花市', en: 'Columbia Road Flower Market', desc: '只有週日早上才有的百年花市！整條維多利亞小街被鮮花淹沒，兩側全是獨立小店與咖啡館。今天不逛就要等下週——而你的行程只有這一個週日有空。', price: '免費', hours: '週日 08:00–15:00，越早人越少', duration: '1.5 小時', tube: 'Hoxton / Bethnal Green', map: 'Columbia Road Flower Market, London' },
        { time: '11:30', name: '紅磚巷市集・午餐', en: 'Brick Lane Market', desc: '塗鴉、黑膠、古著、各國街頭小吃——東倫敦的靈魂。必吃：Beigel Bake 24 小時鹽醃牛肉貝果（£7 上下，排隊快）。', price: '免費入場', hours: '週日最熱鬧', duration: '2 小時', tube: 'Shoreditch High Street', map: 'Brick Lane, London' },
        { time: '14:00', name: '老斯皮塔佛德市集', en: 'Old Spitalfields Market', desc: '維多利亞鑄鐵頂棚下的手作與設計市集，有頂棚不怕雨，順逛周邊 Shoreditch 塗鴉牆。', price: '免費入場', duration: '1.5 小時', tube: 'Liverpool Street', map: 'Old Spitalfields Market, London' },
        { time: '16:00', name: '泰特現代 或 回住處補眠', en: 'Tate Modern / Rest', desc: '狀態好：搭地鐵到 Southwark 逛免費的泰特現代（10 樓觀景台免費看河景）；時差襲來就誠實回家瞇一小時，晚上才有精神。', price: '免費', duration: '2 小時', tube: 'Southwark / Blackfriars', map: 'Tate Modern, London' },
        { time: '18:30', name: '與朋友晚餐', en: 'Dinner with Friend', desc: '朋友 17:00 下早場班——行程第一次會合！讓他挑口袋名單，順便拿到在地情報、對一下這兩週的計畫。', price: '£20–35／人', duration: '2 小時', tips: '正式接風晚餐留到明天朋友休假日，今晚輕鬆吃' },
      ],
      rainNote: '花市照常風雨無阻（帶傘）；大雨就把重心移到有頂棚的 Spitalfields 與泰特現代。',
      rainSpots: null,
      dayTips: ['時差第一天：行程刻意排鬆，累了就回家睡，別硬撐', '花市尾聲（14:30 後）花販會出清喊價，但好貨早上才有', 'Beigel Bake 只收現金？近年已可刷卡，但帶點現金保險'],
    },
    {
      id: 'd3', date: '9/7', weekday: '週一', title: '朋友全休日：肯頓・櫻草丘・南岸・接風晚餐',
      theme: '🤝 攝政公園軸線雙人行',
      friend: '朋友今天全休！從市集逛到夜景，一整天同行——比原計畫的「接機半天」升級成完整版。',
      stay: '住朋友家第 3 晚。',
      transport: '地鐵 Camden Town 站起步，沿攝政公園步行軸線南下，傍晚移動到南岸。本日交通費約 £6–9。',
      spots: [
        { time: '10:30', name: '肯頓市集', en: 'Camden Market', desc: '龐克發源地的水岸市集：運河邊的 Camden Lock、馬廄市集的古董攤、上百家街頭小吃。倫敦最「不英國」的角落。', price: '免費入場', hours: '每日 10:00–18:00', duration: '2 小時', tube: 'Camden Town', map: 'Camden Market, London' },
        { time: '12:30', name: '攝政運河散步 → 攝政公園', en: 'Regent\'s Canal & Regent\'s Park', desc: '沿運河步道從肯頓走進攝政公園（約 30 分鐘），穿過瑪麗皇后玫瑰園——9 月初玫瑰還在尾聲花期。', price: '免費', duration: '1.5 小時', map: 'Queen Mary\'s Rose Gardens, London' },
        { time: '14:00', name: '櫻草丘看天際線', en: 'Primrose Hill', desc: '倫敦人最愛的野餐山丘，山頂一次看盡碎片大廈到倫敦眼的天際線——完全免費的百萬景觀，跟朋友坐著聊天曬太陽。', price: '免費', duration: '1 小時', tube: 'Chalk Farm', map: 'Primrose Hill, London' },
        { time: '16:30', name: '南岸暖身散步・倫敦眼', en: 'South Bank & London Eye', desc: '地鐵到 Waterloo，沿泰晤士河南岸從倫敦眼散步到西敏橋，傍晚金色時刻拍大笨鐘，把明天起的地標先「預習」一遍。', price: '散步免費／倫敦眼 £29 起', duration: '2 小時', tube: 'Waterloo', book: { label: '倫敦眼購票', url: 'https://www.londoneye.com/tickets-and-prices/' }, map: 'London Eye, South Bank, London' },
        { time: '19:00', name: '接風晚餐', en: 'Welcome Dinner', desc: '正式接風！讓在地的朋友挑他的口袋名單，記得把台灣伴手禮帶著給他。', tips: '南岸 Wahaca、Flat Iron 都是不踩雷選項；鳳梨酥、茶葉是英國留學圈最想念的味道' },
      ],
      rainNote: '雨天改室內版：',
      rainSpots: [
        { time: '10:30', name: '肯頓市集（大半有頂棚）', en: 'Camden Market', desc: '馬廄市集區多在室內，照逛。', price: '免費', duration: '2 小時', tube: 'Camden Town', map: 'Camden Market, London' },
        { time: '13:30', name: 'V&A 博物館', en: 'V&A Museum', desc: '和朋友改逛世界最大裝飾藝術博物館（免費），中庭咖啡廳喝下午茶。', price: '免費', duration: '2.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
        { time: '17:00', name: '柯芬園＋晚餐', en: 'Covent Garden', desc: '玻璃頂棚市集不怕雨，晚餐在 Seven Dials Market 室內美食街。', price: '免費', duration: '2.5 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['朋友全休日一共兩天（今天＋9/14 白崖），好好把握', '櫻草丘夕陽時段也很讚——若下午想多留肯頓，可把櫻草丘移到日落前', '明天開始進入景點主線：今晚回家先把西敏寺、衛兵交接的門票與時間確認一遍'],
    },
    {
      id: 'd4', date: '9/8', weekday: '週二', title: '西敏經典：國會大廈・衛兵交接・國家美術館',
      theme: '🏛️ 倫敦必看首日',
      friend: '朋友白天有空（晚上有演出）：衛兵交接、國家美術館、下午茶都可同行，17:00 下午茶結束正好目送他去上班。',
      stay: '住朋友家第 4 晚。',
      transport: '全天步行 + 地鐵。起點：Westminster 站（Jubilee / District / Circle 線）。本日交通費約 £5–7（景點間全步行，僅往返共 2–3 趟地鐵；日上限 £8.9 封頂）。',
      spots: [
        { time: '09:00', name: '大笨鐘與國會大廈', en: 'Big Ben & Houses of Parliament', desc: '西敏橋上拍大笨鐘全景，晨光角度最美。', price: '免費（外觀）', duration: '30 分鐘', tube: 'Westminster', map: 'Big Ben, London' },
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '英王加冕與皇室婚禮場地，牛頓、達爾文長眠於此。線上預訂較便宜且保證入場。', price: '£27（線上）/ £31（現場）', hours: '週一至五 09:30–15:30', duration: '1.5 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://tickets.westminster-abbey.org' }, map: 'Westminster Abbey, London' },
        { time: '11:00', name: '白金漢宮衛兵交接', en: 'Changing of the Guard', desc: '今天（9/8 週二）正好有衛兵交接！建議 10:40 前抵達卡位（維多利亞女王紀念碑階梯視野好）。', price: '免費', hours: '11:00 開始，約 45 分鐘', duration: '1–1.5 小時', tube: 'Green Park / St James’s Park', book: { label: '出發前確認場次', url: 'https://www.householddivision.org.uk/changing-the-guard-calendar' }, map: 'Buckingham Palace, London' },
        { time: '12:30', name: '聖詹姆士公園散步・午餐', en: 'St James’s Park', desc: '穿過公園往特拉法加廣場方向，途中在 Piccadilly 周邊吃午餐（推薦老字號 Fortnum & Mason 食品館或平價連鎖 Pret）。', price: '免費', duration: '1.5 小時', map: 'St James\'s Park, London' },
        { time: '14:00', name: '騎兵總部 Horse Guards', en: 'Horse Guards', desc: '公園走向特拉法加的順路停靠：門口兩位騎在馬上的皇家騎兵站崗，倫敦少數能近距離合照衛兵的地方！穿過拱門就是閱兵廣場。小知識：每天 16:00 的檢閱式源自 1894 年女王抓到衛兵值勤喝酒的百年懲罰傳統。若早上白金漢宮人潮太多，這裡 11:00 也有自己的換崗儀式（人少很多的備案）。', price: '免費（騎兵博物館 £10 左右，馬迷再進）', duration: '20 分鐘', tube: 'Charing Cross / Westminster', map: 'Horse Guards, Whitehall, London' },
        { time: '14:30', name: '國家美術館（精華版）', en: 'National Gallery', desc: '梵谷《向日葵》、莫內、達文西真跡，全部免費！2026 年適逢建館 200 週年。今天走 45 分鐘精華版（梵谷廳 → 莫內 → 達文西），15:20 收工走 10 分鐘到 Soho 喝下午茶。', price: '免費', hours: '每日 10:00–18:00', duration: '45 分鐘', tube: 'Charing Cross', book: { label: '官網資訊', url: 'https://www.nationalgallery.org.uk/visiting/plan-your-visit' }, map: 'National Gallery, London' },
        { time: '15:30', name: '🫖 英式下午茶（與朋友・自 9/15 挪來）', en: 'Afternoon Tea', desc: '9/15 讓位給科茲窩團，下午茶挪到今天——朋友週二白天本來就有空，喝到 17:00 正好目送他去上班。⚠️ 記得先跟朋友確認時間。三選一：Cutter & Squidge（Soho 創意甜點，£32.5）／Cinnamon Bazaar（英印風，£27.5）／奢華首選 Fortnum & Mason（£70 上下，就在中午經過的食品館樓上）。多數需預約。吃很飽，晚上中國城可改輕食。', price: '£27.5–85／人', duration: '1.5 小時', book: { label: 'Cutter & Squidge 預約', url: 'https://cutterandsquidge.com/pages/afternoon-tea' }, map: 'Cutter and Squidge, Soho, London' },
        { time: '17:00', name: '特拉法加廣場 → 皮卡迪利圓環', en: 'Trafalgar Square → Piccadilly Circus', desc: '朋友去上班後自己散步逛市中心霓虹，順路逛萊斯特廣場的 LEGO 旗艦店（有大笨鐘樂高）與 M&M’s World；廣場旁的 Cecil Court 書店古董巷據說是「斜角巷」靈感來源之一，哈迷必繞。17:00–18:45 在中國城（Chinatown）吃晚餐。', price: '免費', duration: '2 小時', map: 'Cecil Court, London' },
        { time: '19:30', name: '🎭 歌劇魅影（選看・40 週年檔期）', en: 'The Phantom of the Opera', desc: '2026 正是魅影 40 週年（1986 年就在這座劇院首演），百老匯明星 Jordan Donica 主演！His Majesty’s Theatre 就在皮卡迪利圓環旁走路 2 分鐘，行程無縫接軌。官網 £25 起免手續費，40 週年需求高建議提前訂；選位首推 Stalls 中段（水晶吊燈就在頭上）。備選場次：9/10（四）牛津回來後、9/16（三）道別壓軸場；週三六另有 14:30 午場、週日休演。', price: '£25–120（Day Seats £37.5 每天 10:00 釋出）', hours: '19:30 開演，全長 2.5 小時', duration: '2.5 小時', tube: 'Piccadilly Circus', book: { label: '官網訂票', url: 'https://uk.thephantomoftheopera.com/tickets' }, map: 'His Majesty\'s Theatre, Haymarket, London' },
      ],
      rainNote: '大雨時衛兵交接可能取消，改走全室內路線：',
      rainSpots: [
        { time: '09:30', name: '西敏寺', en: 'Westminster Abbey', desc: '室內參觀不受天氣影響，照原計畫。', price: '£27（線上）', duration: '2 小時', tube: 'Westminster', map: 'Westminster Abbey, London' },
        { time: '12:00', name: '邱吉爾戰時密室', en: 'Churchill War Rooms', desc: '二戰時期的地下指揮部，原汁原味保存，歷史迷必看（全室內）。', price: '約 £32（線上）', hours: '09:30–18:00', duration: '2 小時', tube: 'Westminster', book: { label: '官網訂票', url: 'https://www.iwm.org.uk/visits/churchill-war-rooms' }, map: 'Churchill War Rooms, London' },
        { time: '14:30', name: '國家美術館', en: 'National Gallery', desc: '免費室內看展，待到心滿意足。', price: '免費', duration: '2.5 小時', tube: 'Charing Cross', map: 'National Gallery, London' },
        { time: '17:30', name: '柯芬園（有頂棚）', en: 'Covent Garden', desc: '玻璃頂棚市集，雨天照樣逛：Apple Market 手作攤、街頭藝人、Ladurée 馬卡龍。', price: '免費', duration: '2 小時', tube: 'Covent Garden', map: 'Covent Garden Market, London' },
      ],
      dayTips: ['西敏寺週日不開放觀光，這天（週二）剛好', '💡 免費聽世界級詩班：17:00 的 Evensong 晚禱可免費進西敏寺本堂（不用門票！），時間允許可以再回頭體驗', '午餐省錢招：Tesco / Boots 的 Meal Deal 約 £4–5'],
    },
    {
      id: 'd5', date: '9/9', weekday: '週三', title: '千年倫敦：倫敦塔・塔橋・波羅市場・聖保羅',
      theme: '🏰 歷史與美食日',
      friend: '朋友雙場日（12:00–22:30）：今天單飛，好好當個歷史迷。',
      stay: '住朋友家第 5 晚。今晚邦喬飛在溫布利球場開唱，那一帶住宿暴漲——跟你住的地方無關。',
      transport: '地鐵至 Tower Hill 站起步，全天沿泰晤士河步行為主。本日交通費約 £5–7（沿河步行串點，僅 2–3 趟地鐵）。',
      spots: [
        { time: '09:00', name: '倫敦塔', en: 'Tower of London', desc: '看王冠珠寶（Crown Jewels）要一開門就衝，可省排隊 1 小時。別錯過 Yeoman Warder（皇家衛士）免費導覽，幽默又精彩。', price: '£34.8（線上）', hours: '週二至六 09:00–17:30', duration: '3 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.hrp.org.uk/tower-of-london/visit/tickets-and-prices/' }, map: 'Tower of London' },
        { time: '12:15', name: '塔橋', en: 'Tower Bridge', desc: '登上塔橋走玻璃步道，俯瞰泰晤士河。時間緊可只在橋上拍照（免費）。', price: '£13.4（線上）/ 走過橋免費', hours: '09:30–18:00', duration: '1 小時', tube: 'Tower Hill', book: { label: '官網訂票', url: 'https://www.towerbridge.org.uk/whats-on/entry-to-tower-bridge' }, map: 'Tower Bridge, London' },
        { time: '12:45', name: '聖鄧斯坦教堂遺址花園', en: 'St Dunstan in the East', desc: '二戰炸毀的教堂殘骸長滿藤蔓，市中心的秘密花園——金融城上班族的私藏午休地，免費、超好拍，就在倫敦塔往塔橋的路上。', price: '免費', hours: '08:00–日落', duration: '20 分鐘', tube: 'Monument / Tower Hill', map: 'St Dunstan in the East, London' },
        { time: '13:45', name: '波羅市場・午餐', en: 'Borough Market', desc: '倫敦最棒的美食市集（週三開始熱鬧）。必吃：Kappacasein 起司三明治、Padella 手工義大利麵（排隊名店）、生蠔攤。飯後到市場旁的 Monmouth Coffee 喝一杯倫敦名店手沖；隔壁的 Southwark 大教堂（免費）與金鹿號帆船複製品也順路看看。', price: '免費入場', hours: '週三至六最熱鬧，10:00–17:00', duration: '1.5 小時', tube: 'London Bridge', book: { label: '官網', url: 'https://boroughmarket.org.uk/visit-us/' }, map: 'Borough Market, London' },
        { time: '15:15', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '走千禧橋（哈利波特混血王子開場場景！）過河，登 528 階圓頂看倫敦全景。最後入場 16:00，要抓緊。', price: '£24–27（線上較便宜）', hours: '週三 10:00–16:30', duration: '1.5–2 小時', tube: 'St Paul’s', book: { label: '官網訂票', url: 'https://www.stpauls.co.uk/ticket-types-and-prices' }, map: 'St Paul\'s Cathedral, London' },
        { time: '16:50', name: 'One New Change 頂樓平台', en: 'One New Change Rooftop', desc: '教堂正對面的購物中心，搭免費電梯上 6 樓露台——正對聖保羅圓頂的最佳拍照角度，遊客少、完全免費。', price: '免費', hours: '至 21:00 左右', duration: '20 分鐘', tube: 'St Paul’s', map: 'One New Change, London' },
        { time: '17:30', name: '利德賀市場', en: 'Leadenhall Market', desc: '哈利波特「斜角巷」取景地！維多利亞式拱廊超好拍，此時商家剛下班氛圍最好。', price: '免費', duration: '30 分鐘', tube: 'Monument', map: 'Leadenhall Market, London' },
        { time: '18:00', name: '空中花園（需預約）', en: 'Sky Garden', desc: '35 樓免費空中花園看日落＋夜景。免費票每週一釋出 3 週後場次；沒搶到有兩個免費備胎：隔壁 The Garden at 120（15 樓露天花園，免預約直接上）或 Horizon 22（254 公尺、倫敦最高免費觀景台，需官網預約）。', price: '免費（需預約）', hours: '週一至五至 18:00', duration: '1 小時', tube: 'Monument', book: { label: '免費預約', url: 'https://skygarden.london/booking/' }, map: 'Sky Garden, 20 Fenchurch Street, London' },
        { time: '21:30', name: '倫敦塔鑰匙典禮（選加，需提前搶票）', en: 'Ceremony of the Keys', desc: '倫敦塔 700 年不間斷的夜間鎖門儀式，全程 35 分鐘、莊嚴到起雞皮疙瘩。門票約 £10，每月初 13:00 釋出下下月票、秒殺——想去現在就要搶 9 月票！', price: '約 £10', hours: '每晚 21:30 準時、遲到不得入場', duration: '1 小時', tube: 'Tower Hill', book: { label: '官網搶票', url: 'https://www.hrp.org.uk/tower-of-london/whats-on/ceremony-of-the-keys/' }, map: 'Tower of London' },
      ],
      rainNote: '倫敦塔戶外區域多，大雨改全室內藝文路線：',
      rainSpots: [
        { time: '10:00', name: '泰特現代美術館', en: 'Tate Modern', desc: '免費現代藝術殿堂，由發電廠改建，10 樓觀景台免費看河景。', price: '免費', hours: '10:00–18:00', duration: '2.5 小時', tube: 'Southwark / Blackfriars', map: 'Tate Modern, London' },
        { time: '13:00', name: '波羅市場（有頂棚）・午餐', en: 'Borough Market', desc: '市場大部分有頂棚，雨天照吃不誤。', price: '免費入場', duration: '1.5 小時', tube: 'London Bridge', map: 'Borough Market, London' },
        { time: '15:00', name: '聖保羅大教堂', en: 'St Paul’s Cathedral', desc: '全室內，照原計畫。', price: '£24–27', duration: '2 小時', tube: 'St Paul’s', map: 'St Paul\'s Cathedral, London' },
        { time: '17:30', name: '利德賀市場 + 空中花園', en: 'Leadenhall & Sky Garden', desc: '拱廊有頂棚、Sky Garden 全室內，雨天照走。', price: '免費', duration: '1.5 小時', tube: 'Monument', map: 'Leadenhall Market, London' },
      ],
      dayTips: ['倫敦塔 + 塔橋 + 聖保羅都排同一天門票不便宜（約 £75），預算有限可挑倫敦塔 + 其他免費景點', '不想付聖保羅門票？17:00 的 Evensong 晚禱可免費入內聽詩班（觀光參觀才收費）', '戲劇迷加碼：南岸的莎士比亞環球劇場站票只要 £5，體驗伊莉莎白式露天劇場', 'Padella 現在採虛擬排隊：到店掃 QR code 登記後先去逛市場，輪到會通知'],
    },
    {
      id: 'd6', date: '9/10', weekday: '週四', title: '一日遊①：牛津大學城（全日深度版）',
      theme: '🎓 學院巡禮',
      friend: '朋友白天有空、晚上有演出：若他願意早起，牛津可同行——搭 16:00 回程火車，18:00 前回到倫敦來得及上班。',
      stay: '住朋友家第 6 晚（最後一晚，明早帶行李搬去 Fulham）。今天去牛津，07:50 的火車要抓好時間。',
      transport: '去程：Paddington → Oxford 火車（直達約 1 小時，Advance 票 £6.5–10，提前買！）。牛津市區全程步行。本日交通費約 £18–25（火車來回 £13–20 ＋市區地鐵 £5）。',
      spots: [
        { time: '07:50', name: '搭火車前往牛津', en: 'Paddington → Oxford', desc: '提前 12 週釋票，Advance 票最低 £6.5。用 GWR 官網或 Trainline 買電子票。', price: '£6.5–10（Advance）', duration: '1 小時', book: { label: 'GWR 訂票', url: 'https://www.gwr.com' }, map: 'Oxford Railway Station' },
        { time: '09:30', name: '基督堂學院', en: 'Christ Church College', desc: '哈利波特霍格華茲大餐廳的靈感原型！含大餐廳與座堂的多媒體導覽。門票每週五釋出，務必提早線上預約。', price: '£22.5–24.5', hours: '依學院行事曆，先查官網', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.chch.ox.ac.uk/visit/tickets-and-information' }, map: 'Christ Church, Oxford' },
        { time: '11:30', name: '波德里安圖書館・嘆息橋', en: 'Bodleian Library & Bridge of Sighs', desc: 'Radcliffe Camera 圓頂圖書館外觀必拍；想進 Divinity School（哈利波特醫護室場景）可參加 30 分鐘導覽（£12.5）。', price: '外觀免費／導覽 £12.5 起', duration: '1 小時', book: { label: '導覽預約', url: 'https://visit.bodleian.ox.ac.uk/tours/library-guided-tours' }, map: 'Radcliffe Camera, Oxford' },
        { time: '12:30', name: '牛津有頂市場・午餐', en: 'Covered Market', desc: '1774 年開業的老市場，推薦 Ben’s Cookies 創始店與傳統英式派。', price: '午餐約 £8–15', duration: '1 小時', map: 'Covered Market, Oxford' },
        { time: '14:00', name: '徹韋爾河撐篙 或 艾許莫林博物館', en: 'Punting / Ashmolean', desc: '天氣好：Magdalen Bridge 船屋租撐篙船體驗劍河風情（約 £30–40／船／小時）；想輕鬆點就去 Ashmolean 博物館（免費，英國最古老博物館）。', price: '撐篙約 £30–40／艾許莫林免費', duration: '1.5 小時', book: { label: '撐篙資訊', url: 'https://www.oxfordpunting.co.uk' }, map: 'Magdalen Bridge Boathouse, Oxford' },
        { time: '16:00', name: '火車回倫敦', en: 'Oxford → Paddington', desc: '17:00 出頭回到 Paddington；朋友同行的話正好趕上晚上上班，你則可以續攤逛 Paddington 周邊或早點回家休息。', price: 'Advance 票另計', duration: '1 小時', map: 'Paddington Station, London' },
      ],
      rainNote: '牛津主要景點都在室內，雨天照走；撐篙改成：',
      rainSpots: [
        { time: '14:00', name: '艾許莫林博物館', en: 'Ashmolean Museum', desc: '免費、英國最古老的公共博物館，埃及木乃伊到拉斐爾素描都有，雨天待兩小時剛剛好。', price: '免費', hours: '10:00–17:00', duration: '2 小時', map: 'Ashmolean Museum, Oxford' },
      ],
      dayTips: ['火車 Advance 票綁定班次、不可退款，時間抓寬鬆一點', '嫌自助麻煩可跟團：KKday 有牛津+劍橋中文一日遊（約 NT$3,235），但自助搭火車更自由省錢', '🎭 魅影備選場次：17:15 回到 Paddington 後，趕 19:30 His Majesty’s Theatre 的晚場時間充裕（若 9/8 沒看成）'],
    },
    {
      id: 'd7', date: '9/11', weekday: '週五', title: '大英博物館・9¾ 月台・晚上看朋友的演出',
      stay: '⚠️ 換宿日：早上帶行李離開朋友家 → Boutique Studios Fulham（Fulham Broadway，入住 15:00 起，先傳訊問可否早寄放行李）。Fulham 第 1 晚。看完朋友演出、在 stage door 等到他之後，記得今晚是回 Fulham、不是回他家。末班車時間先查好。',
      theme: '🎭 文明瑰寶與朋友的舞台',
      friend: '今晚是重頭戲：去朋友的劇院看他的演出！晚上不排其他行程，散場等他一起回家。',
      transport: '地鐵為主：Tottenham Court Road → King’s Cross → Covent Garden → 劇院區。本日交通費約 £6–9（3–4 趟地鐵，日上限 £8.9 封頂）。',
      spots: [
        { time: '10:00', name: '大英博物館', en: 'British Museum', desc: '羅塞塔石碑、帕德嫩神殿雕刻、埃及木乃伊，世界文明一次看完，免費！建議線上預約免費時段票優先入場。注意：2026 西翼整修，部分展廳輪流關閉，出發前查官網。', price: '免費', hours: '10:00–17:00（週五至 20:30）', duration: '3 小時', tube: 'Tottenham Court Road', book: { label: '免費預約', url: 'https://www.britishmuseum.org/visit' }, map: 'British Museum, London' },
        { time: '13:30', name: '午餐：Dishoom King’s Cross', en: 'Dishoom', desc: '倫敦最紅的孟買風餐廳，培根捲餅（Bacon Naan）與黑扁豆咖哩必點。不接受 6 人以下訂位，13:30 後排隊較短。', price: '約 £15–25／人', duration: '1.5 小時', map: 'Dishoom King\'s Cross, London' },
        { time: '15:00', name: '王十字車站 9¾ 月台', en: 'Platform 9¾, King’s Cross', desc: '推行李車進牆的經典拍照點（免費排隊自拍，官方攝影另收費），旁邊就是哈利波特官方商店。拍完往車站後方走 5 分鐘：攝政運河上的百年駁船書店 Word on the Water（屋頂常有爵士演出）＋ Coal Drops Yard 文創街區。', price: '免費', duration: '1.5 小時', tube: 'King’s Cross St. Pancras', map: 'Word on the Water, King\'s Cross, London' },
        { time: '16:30', name: '回家休息・整裝', en: 'Rest & Refresh', desc: '下午提早收工回朋友家休息，晚上才有精神好好看秀。', duration: '1.5 小時' },
        { time: '18:00', name: '劇院附近輕鬆晚餐', en: 'Pre-show Dinner', desc: '在朋友的劇院附近簡單吃（西區劇院周邊很多 pre-theatre menu，兩道式約 £20–25）。時間夠可繞去柯芬園旁的 Neal’s Yard 彩虹小院（20 分鐘）拍照。', price: '£15–25／人', duration: '1 小時', map: 'Neal\'s Yard, Covent Garden, London' },
        { time: '19:30', name: '🎭 朋友的劇院看演出', en: 'Friend’s Show', desc: '今晚專程去捧場！記得先跟朋友確認場次與購票方式（劇組有時有親友票 comps 或員工折扣，先問他別急著自己買）。散場後在 stage door 等他，一起回家聊今晚的演出。', price: '票價依劇目（先問朋友）', duration: '3 小時' },
      ],
      rainNote: '本日行程幾乎全室內，天然防雨！大雨時只需把柯芬園戶外閒逛縮短。',
      rainSpots: null,
      dayTips: ['想另外看音樂劇（獅子王／Wicked／歌劇魅影）可挑其他晚上，用 TodayTix 搶 £25 專區票', '哈利波特迷加碼：舞台劇《被詛咒的孩子》兩部曲版本 2026/9 是最後檔期，可考慮週六日場', '大英博物館旁加碼：Sir John Soane’s Museum（免費、週三至日開），建築師故居塞滿古董的「藏品迷宮」', '哈迷場景補完：Australia House（古靈閣內景，只能看外觀）在 Temple 站附近', '週五大英博物館開到 20:30，白天行程可自由延長'],
    },
    {
      id: 'd8', date: '9/12', weekday: '週六', title: '一日遊②：溫莎城堡・巨石陣・巴斯（KKday 中文團 ✅ 已訂）',
      theme: '🏰 一天收三大經典',
      friend: '朋友雙場日：單飛跟團剛剛好。今天 20:00 才回到市區、他 22:30 才下班，想見面就約宵夜，不然直接明天見。',
      stay: 'Fulham 第 2 晚（不用退房，續住到 9/16）。⏰ 全程最早出門的一天：07:30 集合、08:00 準時發車且逾時不候，抓 06:30 出門。前一晚先把防風外套、行動電源、早餐、護照備好放門口，鬧鐘設兩個。',
      transport: '🚇 去程（實走約 30 分，抓 45 分）：12 Halford Road → Fulham Broadway 站（650m、步行約 9 分）→ District 線 6 站到 Victoria（約 13 分）→ 步行 5 分到 Grosvenor Gardens Stop Z6。⚠️ 上車前先看車頭終點站：要搭往 Upminster／Tower Hill／Barking 方向才會經過 Victoria；若上到往 Edgware Road 的車，它會在 Earl’s Court 轉往北邊，記得在 Earl’s Court 下車換車。🚌 不想在月台判斷方向就搭公車：Fulham Broadway 站外的 11 號公車經 King’s Road、Sloane Square、Victoria Coach Station 直達 Victoria，全程不用轉車、05:15 起營運約 10 分一班（車程約 30–35 分，比地鐵慢但不會搭錯方向）。🚇 回程：20:00 在 Gloucester Road 站解散，同一條 District 線往西 3 站直接回 Fulham Broadway（約 7 分），20:30 前到家。本日交通費約 £5——遊覽車與三張門票都含在團費裡，只花往返集合點的地鐵。',
      spots: [
        { time: '06:30', name: '🚪 從 Fulham 公寓出發', en: 'Depart Accommodation', desc: '走 650m 到 Fulham Broadway 站（約 9 分）。週六早班車班距比平日疏，寧可早到站等車也別賭下一班——這團逾時不候且不退費。出門前檢查：防風外套、行動電源、護照、早餐。', duration: '45 分鐘（含車程）', tube: 'Fulham Broadway', map: '12 Halford Road, London SW6 1JT' },
        { time: '07:15', name: '📍 Grosvenor Gardens Stop Z6 集合', en: 'Meeting Point', desc: '集合 07:30、08:00 準時發車、逾時不候，抓 07:15 到留 15 分緩衝。站牌在 50 Grosvenor Gardens 門口，Victoria 站東南側出口步行 5 分。✅ 已訂「中文導覽－全部入場」，牌價 NT$7,504 折 600 後<strong>實付 NT$6,904</strong>，溫莎城堡＋巨石陣＋羅馬浴場三張門票都含在票價內，現場不用再買任何票。', price: 'NT$6,904（已付）', duration: '全日 12 小時', book: { label: 'KKday 訂單頁', url: 'https://www.kkday.com/zh-tw/product/1193-windsor-castle-stonehenge-bath-london-day-tour' }, map: 'Grosvenor Gardens, London SW1W 0DH' },
        { time: '10:00', name: '溫莎城堡', en: 'Windsor Castle', desc: '英國皇室千年行宮：國家外交大廳、瑪麗皇后玩偶屋、聖喬治教堂（女王長眠處），運氣好遇到衛兵交接。⚠️ 遊客多、安檢排隊會吃掉停留時間，一下車先直奔入口，紀念品最後再說。室內禁止拍照，大背包要寄存（費用自理）。', price: '門票已含', duration: '1.5 小時', map: 'Windsor Castle' },
        { time: '13:00', name: '巨石陣', en: 'Stonehenge', desc: '5,000 年的史前謎團，UNESCO 世界遺產。索爾茲伯里平原上完全沒遮蔽、風又大，防風外套一定要穿。只能走木棧道，嚴禁跨越圍籬靠近石頭（會高額罰款）。遊客中心有新石器時代房屋複製品與考古特展。', price: '門票已含', duration: '1.5 小時', map: 'Stonehenge' },
        { time: '16:00', name: '巴斯・羅馬浴場', en: 'Bath & Roman Baths', desc: '喬治王朝優雅古城＋英國唯一天然溫泉羅馬浴場，入場含語音導覽。時間夠可順走普爾特尼橋與巴斯修道院（都在浴場旁 5 分鐘內）。館內禁止飲食、文物區禁閃光燈、池水禁止碰觸。', price: '門票已含', duration: '1.5 小時', map: 'Roman Baths, Bath' },
        { time: '17:30', name: '從巴斯返回倫敦', en: 'Return Drive', desc: '車程約 2.5 小時，可以在車上補眠。實際抵達時間受交通影響，導遊會在車上說明。', duration: '2.5 小時' },
        { time: '20:00', name: '🚇 Gloucester Road 站解散', en: 'Tour Ends', desc: '解散點步行 2–3 分鐘就到地鐵站，而且剛好在 District 線上，回 Fulham Broadway 只要 3 站約 7 分。晚餐直接回 Fulham 附近吃或超市買——今晚不要再排任何行程，明天哈利波特影城要早起。', duration: '—', tube: 'Gloucester Road', map: 'Gloucester Road Station, London' },
      ],
      rainNote: '☔ 團已訂、雨天照出，不需要備案——把雨具帶好就好。三個景點中溫莎城堡與羅馬浴場都以室內為主，只有巨石陣完全露天；平原上風大，雨傘會開花，帽兜式防水外套比傘實用。',
      rainSpots: null,
      dayTips: ['⚠️ 導遊只在車上導覽，不會陪同進入溫莎城堡、巨石陣、羅馬浴場——每個景點下車時務必跟導遊確認「幾點、在哪裡上車」，並把遊覽車拍照存證（車牌＋停車位置）', '每個點只停 1.5 小時，節奏很趕。1,414 則評論裡最常見的抱怨就是「趕」——先想好每個點你最想看的兩三樣，其餘放掉', '午餐自理、團上沒安排餐廳——前一晚或早上先在 Fulham 超市買好帶著，景點周邊物價高又要排隊，會吃掉本來就不多的停留時間', '溫莎城堡國家外交大廳會不定期關閉（玩偶屋與畫廊照常開）；若整座城堡關閉，團會改去漢普敦宮，不退費。衛兵交接也不保證看得到', '🛁 巴斯只有 90 分鐘，下車前先決定怎麼用：羅馬浴場門票已含、語音導覽快走約 60 分鐘，剩下 30 分鐘走隔壁的巴斯修道院＋普爾特尼橋（都在 3 分鐘內）剛剛好。⚠️ 皇家新月樓單程要走 12–15 分鐘，來回就吃掉 30 分鐘，這團塞不下——想看喬治亞建築就往浴場旁的圓形廣場方向走，別衝新月樓，遊覽車不等人', '取消政策：9/9（三）之前可免費取消；9/10 起不可取消、不可更改、不退款', '這團中文方案有註明「視當日需求可能出現雙語導覽」，評論也提過導遊中英切換——聽不清楚就直接請導遊再講一次中文，不用客氣', '✅ 科茲窩已定案 9/15（Klook 中文 8 人小團）：同樣在 Victoria 集合，但站牌不同——今天是 Grosvenor Gardens Z6、9/15 是車站正門對面的 Stop 11，別記混'],
    },
    {
      id: 'd9', date: '9/13', weekday: '週日', title: '一日遊③：哈利波特影城＋週日烤肉之夜',
      theme: '⚡ 魔法世界朝聖',
      friend: '朋友早場（12:00–17:00）：你白天進影城，傍晚他下班正好會合吃 Sunday Roast！',
      stay: 'Fulham 第 3 晚（今天不用換宿，行李都在 Fulham）。影城日輕鬆，晚上跟朋友吃完 Sunday Roast 後回 Fulham。',
      transport: 'Euston → Watford Junction 火車（直達 20 分鐘，£13.4，可感應付款）→ 官方接駁巴士 15 分鐘（出示影城門票免費搭）。本日交通費約 £20–32（影城火車來回＋市區地鐵）。',
      spots: [
        { time: '09:00', name: '火車前往 Watford Junction', en: 'Euston → Watford Junction', desc: '車站外跟著指標搭哈利波特彩繪接駁車，每 30 分鐘一班。', price: '火車 £13.4 + 接駁免費', duration: '40 分鐘', map: 'Watford Junction Station' },
        { time: '10:30', name: '華納兄弟哈利波特影城', en: 'Warner Bros. Studio Tour', desc: '原版拍攝場景：大餐廳、斜角巷、9¾ 月台、禁忌森林、霍格華茲城堡模型。奶油啤酒必喝！⚠️ 不售現場票，9 月場次常提前 6–8 週售罄——現在就要訂！DIY（火車+門票約 £75）比含車套裝（KKday NT$4,852）省近四成。', price: '門票 £58.5 起', hours: '全程約 4–5 小時', duration: '4.5 小時', book: { label: '官網訂票（快售罄）', url: 'https://www.wbstudiotour.co.uk/tickets/' }, map: 'Warner Bros. Studio Tour London' },
        { time: '16:00', name: '回程進市區', en: 'Return', desc: '搭接駁＋火車回 Euston，順路回家放戰利品。', duration: '1 小時', map: 'Euston Station, London' },
        { time: '18:00', name: '週日烤肉晚餐（與朋友）', en: 'Sunday Roast Together', desc: '朋友 17:00 下班，一起吃英國週日傳統大餐：約克夏布丁＋烤牛肉＋肉汁。Hawksmoor 是名店（建議訂位），或讓朋友帶路去他愛的 gastropub。', price: '£25–40／人', duration: '2 小時', book: { label: 'Hawksmoor 訂位', url: 'https://thehawksmoor.com' }, map: 'Hawksmoor Seven Dials, London' },
      ],
      rainNote: '影城全室內不受影響；回程若下雨，晚餐前的空檔改逛室內的 St Pancras 車站建築與 Coal Drops Yard。',
      rainSpots: null,
      dayTips: ['影城門票含中文語音導覽選項', '影城內餐點普通偏貴，可先吃早午餐再進場', 'Sunday Roast 熱門店週日會滿，提早幾天訂位'],
    },
    {
      id: 'd10', date: '9/14', weekday: '週一', title: '一日遊④：七姊妹白崖（朋友休假日・全天同行！）',
      theme: '🤝 白崖健行雙人行',
      friend: '朋友全天休假——本週最重要的同行日！一起去看英格蘭最震撼的海岸線。',
      stay: 'Fulham 第 4 晚。',
      transport: '自助：Victoria → Seaford 火車（Lewes 轉車一次，約 1.5 小時，來回約 £25–32）。或跟中文團（超便宜）：KKday「陪爬陪拍」團 NT$1,228、Klook 版 NT$1,036。本日交通費：自助約 £37–44（火車來回＋沿海公車一日券 £9＋市區地鐵）／跟團約 £5。',
      spots: [
        { time: '08:00', name: '火車 Victoria → Seaford', en: 'London Victoria → Seaford', desc: '和朋友一起搭火車南下，在 Lewes 轉車一次。', price: '來回約 £25–32', duration: '1.5 小時', book: { label: 'Southern 訂票', url: 'https://www.southernrailway.com' }, map: 'Seaford Station' },
        { time: '10:00', name: 'Seaford Head 步道', en: 'Seaford Head', desc: '沿崖頂步道走到 Cuckmere Haven，這裡是拍七姊妹白崖經典角度（含海岸警備小屋前景）的最佳位置。', price: '免費', duration: '2.5 小時（來回約 5 公里）', map: 'Seaford Head, Seaford' },
        { time: '13:00', name: '午餐＋七姊妹鄉村公園', en: 'Seven Sisters Country Park', desc: '在 Exceat 遊客中心午餐，沿 Cuckmere 河谷步道散步至海口近看白崖。', price: '免費', duration: '2.5 小時', map: 'Seven Sisters Country Park' },
        { time: '16:00', name: '12X 公車 → 布萊頓傍晚遊', en: 'Brighton', desc: '搭 12X 到布萊頓（約 40 分鐘），逛 The Lanes 巷弄與布萊頓碼頭，海邊吃炸魚薯條，再搭直達火車回倫敦（約 1 小時）。', price: '公車一日券 £9', duration: '2.5 小時', map: 'Brighton Palace Pier' },
      ],
      altNote: '不想研究交通？中文團「陪爬陪拍」版（布萊頓+七姊妹+比奇角）：',
      altSpots: [
        { time: '08:00', name: '倫敦市區集合出發', en: 'Tour Departure', desc: 'KKday 中文團 NT$1,228（4.9 分、售出 300+，出發前建微信群）或 Klook 版 NT$1,036。含七姊妹健行、Beachy Head 燈塔拍照指導、布萊頓市區約 3 小時。', price: 'NT$1,036–1,228／人', duration: '全日 10 小時', book: { label: 'KKday 訂購', url: 'https://www.kkday.com/zh-tw/product/285517' }, map: 'Victoria Station, London' },
        { time: '10:30', name: '七姊妹白崖健行＋比奇角', en: 'Seven Sisters & Beachy Head', desc: '導遊帶路走最佳拍照路線，紅白條紋燈塔＋白色斷崖一次收。', price: '含在團費', duration: '3.5 小時', map: 'Beachy Head, Eastbourne' },
        { time: '15:00', name: '布萊頓自由活動', en: 'Brighton', desc: '皇家行宮外觀、The Lanes、碼頭遊樂園，約 21:00 回到倫敦。', price: '午餐自理', duration: '3 小時', map: 'Brighton Palace Pier' },
      ],
      rainNote: '白崖是純戶外行程，雨天和朋友改去溫莎（週一有開）：',
      rainSpots: [
        { time: '09:30', name: '溫莎城堡（室內為主）', en: 'Windsor Castle', desc: '英王行宮，State Apartments 與聖喬治教堂都在室內。Waterloo 直達火車 55 分鐘。', price: '£32（線上預購）', hours: '10:00–17:15（週二三休）', duration: '3 小時', book: { label: '官網訂票', url: 'https://www.rct.uk/visit/windsor-castle' }, map: 'Windsor Castle' },
        { time: '14:30', name: '回倫敦：V&A 博物館＋下午茶', en: 'V&A & Tea', desc: '世界最大裝飾藝術博物館（免費），中庭咖啡廳是全球最美咖啡廳之一，直接在裡面喝下午茶。', price: '免費入場', duration: '2.5 小時', tube: 'South Kensington', map: 'Victoria and Albert Museum, London' },
      ],
      dayTips: ['中文團出發前 2–4 天可免費取消，可先卡位、看天氣預報再決定', '崖頂無圍欄，拍照離邊緣至少 5 公尺', '白崖風大，防風外套必備'],
    },
    {
      id: 'd11', date: '9/15', weekday: '週二', title: '一日遊⑤：科茲窩鄉村小團遊（Klook 中文團 ✅ 已訂）',
      theme: '🏡 蜂蜜色石屋與英式鄉村',
      friend: '朋友週二白天有空，但你整天在科茲窩——原本的下午茶已挪到 9/8 跟他喝（記得先跟他確認）。今晚各忙各的，明晚搬回他家就是告別前夜。',
      stay: 'Fulham 第 5 晚（最後一晚，明早 10:00 前退房）。⏰ 08:10 集合、遲到或未到不退款，抓 07:05 出門。18:30 解散回家後今晚務必打包完——明早退房搬家。',
      transport: '🚇 去程（比 9/12 晚 35 分出門）：07:05 出門 → Fulham Broadway → District 線約 13 分到 Victoria → 火車站 7 號出口正對面的公車月台就是集合點。⚠️ 集合點跟 9/12 不同：9/12 在車站東南側的 Grosvenor Gardens Z6，今天是車站正門對面的 Victoria Station Stop 11（SW1W 9LN），兩者走路 2–3 分鐘——別走錯邊。🚇 回程：18:30 Gloucester Road 解散，District 線往西 3 站回 Fulham Broadway，19:00 前到家。本日交通費約 £5。',
      spots: [
        { time: '07:05', name: '🚪 從 Fulham 公寓出發', en: 'Depart Accommodation', desc: '走 650m 到 Fulham Broadway（約 9 分）搭 District 線。需在出發 5 分鐘前抵達集合點、遲到或未到不退款——寧可早到站著等。', duration: '45 分鐘（含車程）', tube: 'Fulham Broadway', map: '12 Halford Road, London SW6 1JT' },
        { time: '07:50', name: '📍 Victoria Station Stop 11 集合', en: 'Meeting Point', desc: '✅ 已訂 Klook 中文 8 人小團（#209931）NT$3,102，賓士 9 人座。⚠️ 集合點是火車站 7 號出口正對面的公車月台 Stop 11，不是 9/12 的 Grosvenor Gardens！供應商（CKT）出發前一天會建群組發車牌與車輛照片，前一晚還沒收到就找 Klook 客服。08:10 準時出發。', price: 'NT$3,102（已付）', duration: '全日約 10.5 小時', book: { label: 'Klook 訂單頁', url: 'https://www.klook.com/zh-TW/activity/209931-cotswolds-bibury-bourton-day-tour-with-chinese-guide/' }, map: 'Victoria Station, London SW1W 9LN' },
        { time: '10:10', name: '拜伯里', en: 'Bibury', desc: '車程約 2 小時後抵達第一站。威廉莫里斯口中「英格蘭最美村莊」，1380 年的織工石屋 Arlington Row 是英國護照內頁圖案——大眾運輸到不了，這排石屋就是你跟團的理由。', price: '免費入場', duration: '45 分鐘', map: 'Arlington Row, Bibury' },
        { time: '11:35', name: '水上伯頓・午餐', en: 'Bourton-on-the-Water', desc: '「科茲窩的威尼斯」：溫德拉什河穿鎮、五座低石橋相連，全團停最久的一站（1.5 小時＋30 分午餐），河畔慢走、喝杯咖啡都來得及。午餐自理：河邊 fish & chips 或麵包店外帶，別點慢出餐的。', price: '午餐自理約 £10–15', duration: '2 小時', map: 'Bourton-on-the-Water' },
        { time: '13:45', name: '上斯勞特・下斯勞特', en: 'Upper & Lower Slaughter', desc: '遊客最少的雙子村：下斯勞特的 19 世紀老磨坊與小溪是明信片場景。名字來自古英語「泥濘地」，跟屠宰無關。各停 15 分鐘。', price: '免費入場', duration: '30 分鐘', map: 'Lower Slaughter' },
        { time: '14:45', name: '斯托「魔戒之門」', en: 'St Edward’s Church, Stow', desc: '聖愛德華教堂北門：兩棵百年紫杉夾著木門，傳為托爾金「都林之門」靈感來源。20 分鐘拍照剛好。', price: '免費入場', duration: '20 分鐘', map: 'St Edward\'s Church, Stow-on-the-Wold' },
        { time: '15:25', name: '奇平卡姆登', en: 'Chipping Campden', desc: '科茲窩「羊毛之都」：蜂蜜色石灰岩主街與 1627 年市集廳，最後一站悠閒收尾。', price: '免費入場', duration: '40 分鐘', map: 'Chipping Campden' },
        { time: '18:30', name: '🚇 Gloucester Road 解散', en: 'Tour Ends', desc: 'District 線往西 3 站回 Fulham Broadway（約 7 分），19:00 前到家。晚餐 Fulham 附近解決，然後打包——明早 10:00 前退房搬回朋友家。', duration: '—', tube: 'Gloucester Road', map: 'Gloucester Road Station, London' },
      ],
      rainNote: '☔ 科茲窩以戶外為主。預報普通就照去（雨中石屋村另有氛圍，評論裡雨天團照樣五星）；預報真的很爛就用「24 小時前免費取消」全額退，當天自動變回原本的博物館室內日：',
      rainSpots: [
        { time: '10:00', name: '自然史博物館＋V&A', en: 'NHM & V&A', desc: '取消跟團時的替代方案（原 9/15 行程）：藍鯨骨架大廳、恐龍廳，隔壁 V&A 看時尚廳與 Cast Courts 石膏像中庭。都免費。', price: '免費', hours: '10:00–17:50', duration: '3.5 小時', tube: 'South Kensington', map: 'Natural History Museum, London' },
        { time: '15:30', name: '牛津街・攝政街購物', en: 'Oxford St & Regent St', desc: 'Selfridges（4 樓 Jellycat 專區，見口袋名單）、Liberty 百年木造百貨、Hamleys，逛到晚餐。', price: '免費入場', duration: '3 小時', tube: 'Oxford Circus', map: 'Liberty London, Regent Street' },
      ],
      dayTips: ['⏰ 取消期限：活動前 24 小時（英國時間）＝最晚 9/14 上午 08:10 前（台灣同日 15:10），以 Klook 訂單頁顯示為準。9/13 起盯天氣預報決定去留', '供應商出發前一天會拉群組發車輛照片＋車牌——前一晚還沒收到通知就主動聯繫 Klook 客服', '連三天早起的第二天（昨七姊妹、今科茲窩、明搬家），今晚回家先打包再耍廢', '原 9/15 的內容去向：下午茶挪 9/8（與朋友）、自然史快閃塞 9/16 下午（選逛）、牛津街購物用 9/16 晚上＋9/17 下午補', '鄉村路彎多、村內石板路多：穿好走的鞋，會暈車先吃暈車藥再上車'],
    },
    {
      id: 'd12', date: '9/16', weekday: '週三', title: '格林威治半日遊・肯辛頓宮・Flat Iron 告別牛排',
      theme: '🚢 子午線與宮殿',
      friend: '朋友雙場日：最後的單飛日，把想逛的補完。',
      stay: '⚠️ 換宿日：早上 10:00 前從 Fulham 退房 → 行李寄放或直接送朋友家 → 晚上住朋友家（告別前夜，已確認）。今晚起到回程都在朋友家，行李歸位、開始打包。',
      transport: '上午：Uber Boat 遊船（Tower Pier → Greenwich，約 30 分鐘，App 購票較便宜）。下午地鐵回市區。本日交通費約 £14–18（遊船單程 £6.2 起＋DLR/地鐵數趟）。',
      spots: [
        { time: '09:00', name: 'Uber Boat 泰晤士河遊船', en: 'Uber Boat to Greenwich', desc: '從水上看塔橋與金絲雀碼頭天際線，兼具交通與觀光。App 或線上購票比現場便宜。', price: '單程約 £6.2 起', duration: '40 分鐘', book: { label: '購票', url: 'https://www.thamesclippers.com/plan-your-journey/ticket-information' }, map: 'Tower Millennium Pier, London' },
        { time: '10:00', name: '皇家天文台・本初子午線', en: 'Royal Observatory', desc: '雙腳橫跨東西半球！山丘上眺望格林威治全景與倫敦天際線。', price: '£24（線上）', hours: '10:00–17:00', duration: '1.5 小時', book: { label: '官網訂票', url: 'https://www.rmg.co.uk/plan-your-visit/tickets-prices' }, map: 'Royal Observatory Greenwich' },
        { time: '11:30', name: '舊皇家海軍學院・皇后宅邸鬱金香梯', en: 'Old Royal Naval College & Queen\'s House', desc: '天文台下山途經——《雷神索爾》《加勒比海盜》都在這取景，巴洛克雙塔園區免費進入；旁邊免費的 Queen’s House 有全倫敦最好拍的 Tulip Stairs 藍色螺旋梯，別錯過！', price: '園區與皇后宅邸免費／Painted Hall 約 £15', duration: '45 分鐘', map: 'Queen\'s House, Greenwich' },
        { time: '12:15', name: '格林威治市集・午餐', en: 'Greenwich Market', desc: '有頂棚的百年手作市集（每日開放），各國小吃便宜好吃，順便買紀念品。卡蒂薩克號帆船在旁邊可看外觀。', price: '免費入場', duration: '1.5 小時', map: 'Greenwich Market, London' },
        { time: '14:00', name: '肯辛頓宮', en: 'Kensington Palace', desc: '黛安娜王妃故居，今天（週三）有開！State Apartments 與特展。時間不夠或想省門票就改逛海德公園。', price: '£24.7（線上）', hours: '週三至日 10:00–18:00', duration: '2 小時', tube: 'High Street Kensington', book: { label: '官網訂票', url: 'https://www.hrp.org.uk/kensington-palace/visit/tickets-and-prices/' }, map: 'Kensington Palace, London' },
        { time: '16:15', name: '自然史博物館快閃（選逛）', en: 'Natural History Museum', desc: '9/15 讓位給科茲窩的補償場：肯辛頓宮出來走約 20 分（或 High St Kensington 搭 Circle/District 線兩站到 South Kensington），直奔中央大廳看藍鯨骨架與哥德式「動物大教堂」建築本身，45 分鐘夠本。最後入場 17:30。有逛的話牛排改 17:30 前入座，仍在尖峰前。', price: '免費', hours: '10:00–17:50（最後入場 17:30）', duration: '45 分鐘', tube: 'South Kensington', map: 'Natural History Museum, London' },
        { time: '17:00', name: '🥩 Flat Iron Kensington・告別牛排', en: 'Flat Iron Steak', desc: '想吃的那家！招牌 flat iron 牛排 £14（200g，附沙拉與牛油爆米花），離場還送焦糖海鹽冰淇淋（給你冰淇淋刀造型代幣，當場吃或留著去別家分店都行）。⏰ 排 17:00 是刻意的：避開 19:00–21:00 尖峰、週三又是離峰日，幾乎不用等位。從肯辛頓宮走過來只要 6 分鐘。可線上訂位（免費），訂不到也不用慌——他們固定保留大量 walk-in 名額，現場留電話等通知就好，不必站著排隊。', price: '牛排 £14＋配菜約 £5，含飲料一人約 £25–30（另 12.5% 服務費）', hours: '週日–四 12:00–22:30', duration: '1.5 小時', tube: 'High Street Kensington', book: { label: 'Flat Iron 訂位', url: 'https://flatironsteak.co.uk/locations/kensington/' }, map: 'Flat Iron Kensington, 9 Young Street, London W8 5EH' },
        { time: '18:45', name: '最後採買・打包', en: 'Last Shopping & Packing', desc: '超市掃伴手禮（茶葉、餅乾、保養品），回家打包行李。倫敦超市多開到 22:00–23:00，吃完再買時間很夠。明天中午前就要出門了。', duration: '2 小時', map: 'Marks and Spencer, Oxford Street, London' },
      ],
      rainNote: '雨天改全室內輕鬆版：',
      rainSpots: [
        { time: '10:00', name: '肯辛頓宮＋自然史補完', en: 'Kensington Palace', desc: '宮殿全室內；還沒逛夠的南肯辛頓博物館群也在附近。', price: '£24.7', duration: '3 小時', tube: 'High Street Kensington', map: 'Kensington Palace, London' },
        { time: '14:00', name: '利柏堤百貨＆攝政街室內採買', en: 'Liberty & Regent Street', desc: '室內購物補貨：茶葉、圍巾、伴手禮，順便打包前最後巡禮。', price: '免費入場', duration: '2.5 小時', tube: 'Oxford Circus', map: 'Liberty London' },
      ],
      dayTips: ['行李秤一下：國泰「輕便 Light」票種托運通常僅 1 件 23kg——伴手禮買太多先上官網加購行李，比機場現場便宜', '液體（酒、醬料）記得放托運', '🎭 魅影最終備選場：今晚 19:30 可當「道別倫敦」壓軸（週三另有 14:30 午場），明天班機是晚上 20:15、看完隔天睡到自然醒也來得及。真要看的話順序改成：肯辛頓宮 → 17:00 牛排 → 18:30 出發進西區 → 19:30 開演，打包挪到散場後或明早', '🥩 Flat Iron 為什麼排今天：① 就在肯辛頓宮旁邊（走 6 分鐘）② 週三離峰、17:00 又在尖峰前，等位機率最低 ③ 朋友今天雙場上班，單人用餐反而最快有位 ④ 這是回程前最後一個完整的晚上。想提前吃的備案是 9/10（四，牛津回來後晚上全空）', '🥩 訂位建議：官網選 Kensington 分店線上訂免費、兩分鐘搞定。訂不到別緊張——Flat Iron 一向保留大量 walk-in 名額，現場報名字留電話、他們有位就通知，不用站著排。真正要避開的是週五、週六晚上'],
    },
    {
      id: 'd13', date: '9/17', weekday: '週四', title: '道別倫敦 → 台北（晚班機，最後一天很完整）',
      theme: '🏠 返程日・20:15 起飛',
      friend: '朋友白天有空：告別早午餐一路聊到下午，甚至送你上地鐵。',
      stay: '早上從朋友家出發（行李已在他家）。晚班機的好處：白天全部可用。',
      transport: '前往希斯洛 LHR T3：Piccadilly 線直達（住朋友家依位置約 50–70 分）或 Paddington 搭 Elizabeth 線。20:15 起飛，17:15 前到機場報到。本日交通費約 £6–14。',
      spots: [
        { time: '10:00', name: '告別早午餐（與朋友）', en: 'Farewell Brunch', desc: '晚班機的福利：和朋友吃頓不趕時間的英式早午餐——Full English Breakfast 畫下句點。附近咖啡館或 Dishoom 都好。', price: '£12–20／人', duration: '1.5 小時', map: 'Dishoom Covent Garden, London' },
        { time: '12:00', name: '最後採買・補遺珠', en: 'Last Shopping', desc: '下午還有 4 小時可用：超市補伴手禮、牛津街 Selfridges（Jellycat 專區見口袋名單）與攝政街補貨，或把這兩週的遺珠（Sky Garden、V&A、某間沒吃到的店）補掉一個。', price: '依內容', duration: '3 小時', map: 'Oxford Street, London' },
        { time: '16:00', name: '回朋友家取行李 → 出發機場', en: 'To Heathrow', desc: '取行李搭 Piccadilly 線直達 LHR T3（或 Elizabeth 線轉乘），17:15 前抵達報到。行李超過 23kg 的話，先把重物移到隨身包。', price: '£5.6–13.9', duration: '1–1.5 小時', map: 'Heathrow Airport Terminal 3' },
        { time: '20:15', name: 'CX256 起飛 → 香港 → 台北', en: 'LHR → HKG → TPE', desc: 'A350 長程段睡覺剛好；香港轉機 2h30（同一張票，誤點國泰負責改班）。9/18（五）20:05 抵達桃園。回程時差訣竅：機上第二段少睡，抵台當晚正常時間睡。', map: 'Heathrow Airport Terminal 3' },
      ],
      dayTips: ['英國已無購物退稅，別在機場排隊找退稅櫃台（沒有這服務了）', '茶葉、肉品入境台灣規定先查關務署，火腿臘腸類不能帶', '機場 Hamleys／World Duty Free 可做最後補貨，但價格通常比市區貴'],
    },
  ],
};
